### ISSUE TITLE
[BUG] - Scandinavian regens not having faces replaced

### ISSUE THREAD

**Issue by ZanoMeridius** [Maradonna90/NewGAN-Manager#100]
**Describe the bug**
Scandinavian faces appear to not be working. They return a message of "Ethnicity Scandinavian has no faces left for mapping. Skipping player <ID>" no matter whether the Allow Duplicates? checkbox is checked.

**To Reproduce**
1. Go to NewGAN-Manager
2. Load the provided Profile, SvenskaFM2020
3. Select the provided RTF File, 2026_Svenska.rtf
4. Select Mode = Preserve and check the Allow Duplicates? checkbox
5. Replace Faces
6. Check log to see that all new Scandinavian players return the no faces left for mapping, even though Allow Duplicates? checkbox is checked.

**Expected behavior**
Faces are generated for all Scandinavian players

**Screenshots**
N/A - files provided

**Desktop (please complete the following information):**
 Windows

**Attachments**
[newgan_log.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7698252/newgan_log.zip)
[RTF.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7698253/RTF.zip)
[ConfigFiles.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7698254/ConfigFiles.zip)

**Comment by ZanoMeridius** [comment]
Tried with v1.2.1 and confirmed that I am able to Replace Faces with no issues on older version.

Log from 1.2.1 attached
[newgan_log_v1.2.1.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7699384/newgan_log_v1.2.1.zip)
.

**Comment by Maradonna90** [comment]
You are using Football Manager 2020. There might be issues with the view or other parts with the program. Use older versions if they work with older FMs.

**Comment by ZanoMeridius** [comment]
@Maradonna90 there is no way to sustain multiple versions of the install since we cannot select the install directory. Doing this would mean long term a need for users to try to track down the version that works for their version of FM.

There is a decent population of users that continue to use older versions of FM to continue an old save. Transitioning between versions would require the full reinstall process with backing up files to be done every time. Furthermore, unless I’m missing it there is also nothing available on the GitHub to locate old versions of the install meaning those old versions could become unobtainable over time.

I would strongly recommend considering an enhancement to add a FM version value that defaults to the latest. I expect the issue here is the change in regions from FM21 to FM22, and therefore there would just be two versions
currently - FM21 and earlier, and FM22.

In future years this would allow for the continued evolution for changes to new FMs while still sustaining backwards support.

I also realize this could lead to vastly increased complexity from branches of logic across versions so perhaps just sustaining a version history with access to older versions that calls out releases for new FM versions would be a lower maintenance approach if the above is not supportable.
