### ISSUE TITLE
bar gets stuck

### ISSUE THREAD

**Issue by dominatoor90** [Maradonna90/NewGAN-Manager#101]
i have a problem with the new version of newgan manager. if i try to preserve and then generate the bar gets stuck, i left it for hours and no progress. didn't have this problem with the previous versio
![Capture](https://user-images.githubusercontent.com/96006911/145711804-43dae3c9-cf0c-4b64-90d2-57bc883fe30e.JPG)
n

**Comment by Maradonna90** [comment]
Please provide your RTF, config.xml and logfile.

**Comment by dominatoor90** [comment]
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/7702863/newgan.log)

**Comment by dominatoor90** [comment]
rtf and xml are not supported here

**Comment by dominatoor90** [comment]
https://file.io/UbCgSeUKlDLG xml file

**Comment by dominatoor90** [comment]
https://file.io/QeWpDOxGjfUZ rtf file

**Comment by Maradonna90** [comment]
the XML and RTF are gone. Can you just zip them and upload it here?
