### ISSUE TITLE
[BUG] Adding faces to low level squads (not newgens) overwrites default faces

### ISSUE THREAD

**Issue by twointum** [Maradonna90/NewGAN-Manager#103]
**Describe the bug**
Running the tool on a team that has some faces and some silhouettes overwrites all players on the team.

**To Reproduce**
Use the SCRIPT FACES squad filter.
Create RTF file
Run Newgan with Perserve setting.

**Expected behavior**
Don't touch guys with faces already.

Is there a way the built in SCRIPT FACES squad filter can indicate indicate if a player has a face (newgan or built in)? That way I can sort by that and only select the guys without faces.

Thank you for this awesome tool!

**Comment by Maradonna90** [comment]
If you use the filter properly you will just have newgens.
