### ISSUE TITLE
[BUG] NewGAN will not open

### ISSUE THREAD

**Issue by twointum** [Maradonna90/NewGAN-Manager#105]
**Describe the bug**
NewGAN doesn't open. Also, all of my previously face'd player are now silhouettes. I haven't moved any files or made any system settings since the last open.

**To Reproduce**
Click on the icon.

**Expected behavior**
App should open.

**Desktop (please complete the following information):**
 - OS:  Windows 10

**Attachments**
Add your `newgan.log` and RTF-File
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/7766622/newgan.log)

**Comment by Maradonna90** [comment]
Thanks for the log.

Can you zip your `.user` and `.config` folder in `%localappdata%\Programs\NewGAN-Manager\src/newganmanager\` and upload it?

**Comment by Telemachos2018** [comment]
I have the same exact issue. I tried reinstalling the program multiple times:

[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/7770626/newgan.log)

I'm not seeing a "\src/newganmanger\" 
![image](https://user-images.githubusercontent.com/51891475/147272950-512c476d-8e63-4c04-a20e-ad9fc356709e.png)

**Comment by twointum** [comment]
I just reinstalled and everything is fine. I think I am using it wrong. Should I have one RTF for all newgens all time or do I need to create one for each intake? I see that the filter has nothing to do with season or year so does that mean the file will constantly grow? Thanks!

**Comment by Telemachos2018** [comment]
@Maradonna90, for some reason, newgan files were not completely being removed for me when I uninstalled through windows "add or remove programs".

I had to manually delete the remaining files. After doing so, redownloading, and reinstalling- newgan now works. I had removed and reinstalled multiple times prior without any progress.

**Comment by cloverjojo** [comment]
Same issue as well. Tried to uninstall, redownload, install multiple times, the program won't run anyway
[newganmanager.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7773854/newganmanager.zip)
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/7773855/newgan.log)
.

**Comment by Maradonna90** [comment]
@cloverjojo have you delete all remaining files manually as @Telemachos2018 mentioned?

**Comment by Maradonna90** [comment]
@twointum doesnt really matter if you always have one RTF with all players or just an RTF with new ones when using `Preserve`.

**Comment by cloverjojo** [comment]
> 

I did.

**Comment by TravisBickle777** [comment]
Same issue on win10 and have deleted all newgan file in %localappdata% file as well. I've tried many times to uninstall and install, still can not open the app. so I tried to back to use the old ver1.2 to make a camparison, whatever install and uninstall, and delete Newgan file in %localappdata%. it works fine for me. Someone posted on FM-Base forum that it was caused by the check_for_update function in ver1.3, his pc failed to connect to github to get the app version information. Really confused how to run the new ver1.3.  Can you give help to slove the issue? very thankful!
