### ISSUE TITLE
[BUG] NewGAN Manager will not appear in search

### ISSUE THREAD

**Issue by Wadas123** [Maradonna90/NewGAN-Manager#107]
Describe the bug:

Once I use the 1.3 installer for the NewGAN-Manager I can not open it by searching for it in the search bar. I can find the files that it installs in the %localappdata%\Programs\NewGAN-Manager but I can not find a way to open it. I have tried uninstalling the program and deleting the folder in the %localappdata%\Programs\NewGAN-Manager location and nothing has worked.

1. Extract NewGAN-Manager-Installer-Win-v1.3.0.zip
2. Click on windows folder
3. Click on NewGAN-Manager-1.3.0.msi and install (bypassing windows firewall).
4. Click the search bar in bottom left and type in NewGAN.

Expected behavior:

You should be able to see the icon for the NewGAN manager and be able to open it, but this is not happening.

Desktop:

Windows 10

**Comment by Maradonna90** [comment]
this is most likely a windows issue. It happened to some people before

check this: https://answers.microsoft.com/en-us/windows/forum/all/applications-does-not-appear-on-windows-10-search/3f2569b3-df94-4841-bf3e-c5773ecd4ea8
