### ISSUE TITLE
[BUG] Some African players are not getting mapped

### ISSUE THREAD

**Issue by TiagoSousa26** [Maradonna90/NewGAN-Manager#108]
**Describe the bug**
The FM generated the regen I generated the rtf file, ran the NewGAN and some African players are not getting their faces mapped but the other got. Their names are on the rtf file. See screenshots to see some examples even from other clubs.

**To Reproduce**
1. Load the rtf file
2. Choose preserve without duplicates
3. Disable cache and reload the skin
4. Turn cache on

**Expected behavior**
It should be mapping all the regen faces.

**Screenshots**
![imagem](https://user-images.githubusercontent.com/18198433/147830461-5770c033-5188-4454-a1bc-ffa89602851b.png)
![imagem](https://user-images.githubusercontent.com/18198433/147830844-7de26c24-1722-4dc4-ab8f-735edeabd93d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - NewGAN Manager: v1.3.0

**Attachments**
I changed the extension to .txt because it doesn't let to put .rtf files.
[2025-regen-copy.txt](https://github.com/Maradonna90/NewGAN-Manager/files/7796546/2025-regen-copy.txt)

**Comment by TiagoSousa26** [comment]
I also found some Portuguese players that are black that are not having their faces replaced like Samuel Fonte and Rodrigo Nogueira. So it seems to be something related to their ethnicity and not a region like Africa. Could be some problem with my faces folder?

**Comment by Maradonna90** [comment]
thats exactly the case. Try rerun it with "Allow duplicates"

**Comment by TiagoSousa26** [comment]
Ok, thanks. I will try first with the game being in the English language because the "Allow duplicates" isn't solving the problem.

**Comment by TiagoSousa26** [comment]
I tried but neither having the game in English nor having duplicates on solving the problem.

```
2022-01-11 19:21:09,592 | NewGAN Mapper: 51529/65072: ['2002395710', 'GNB', 'POR', '3'], African, SpanMed
2022-01-11 19:21:09,592 | NewGAN Mapper: Ethnicity African has no faces left for mapping. Skipping player 2002395710
```

**Comment by Maradonna90** [comment]
can you give me your RTF in english?

**Comment by TiagoSousa26** [comment]
Here it is
[2025-3-regen.txt](https://github.com/Maradonna90/NewGAN-Manager/files/7919545/2025-3-regen.txt)
