### ISSUE TITLE
NewGan won't open on Mac

### ISSUE THREAD

**Issue by ItsJustJib** [Maradonna90/NewGAN-Manager#109]
**Describe the bug**
I just get an error message with script when I open the file, tried reinstalling a couple times and same error message. Not sure if its anything to do with new Mac OS, honestly don't understand the error message as its showing code rather than a straight forward explanation of what's wrong. Used to work fine on old OS/FM21, haven't actually used Newgan on the new FM until now. Tried reinstalling the 1.3 version as Zealand put out that video saying there was a new version. First attempt at opening it today.

Would appreciate any help!!

**To Reproduce**
Open the file

**Expected behavior**
File should open. 

**Screenshots**
Uploaded screenshot of error code below

**Desktop (please complete the following information):**
 - OS: MACOS Monterey 12.1

**Attachments**
Add your `newgan.log` and RTF-File
![Screenshot 2022-01-05 at 5 52 13 pm](https://user-images.githubusercontent.com/97187974/148265530-7f3b2cd0-1ca9-4220-8f99-1ca6c9293787.png)

**Comment by Maradonna90** [comment]
duplicate #91
