### ISSUE TITLE
error installing NewGAN-Manager

### ISSUE THREAD

**Issue by Johno43** [Maradonna90/NewGAN-Manager#110]
Get those 2 errors pops up while installing this on Windows 11, had to reinstall it due to problems using it. Was working fine before and installed it with no problem. Keep getting those problems :(  Error code 2502 and 2503

https://i.gyazo.com/0722c76ac4eb34f1464c767e429c4cc5.png 
https://i.gyazo.com/d1f0af68adafa94d8e7036e388696e40.png

**Comment by Maradonna90** [comment]
check https://answers.microsoft.com/en-us/windows/forum/all/error-code-2502-and-2503-when-installing/f5a72c98-0fe9-40f9-bcd6-5240c0e33393

this seemed to be a windows specific problem.

**Comment by massivepidas** [comment]
I have this same exact issue.

Error might occur if you're using third party anti-virus software. The newgan windows installer is identified as a trojan malware, with potential rootkit and spyware/keylog. So if you're using third party anti virus software, that might be why
