### ISSUE TITLE
Multiple players not updating

### ISSUE THREAD

**Issue by narion** [Maradonna90/NewGAN-Manager#111]
Several times in my current save after a youth intake I've gone to update the NewGen faces, on a number of occasions I've noticed that multiple players haven't updated to a new face mapping. I can provide the input files that have been used, I've also tried sorting files (following the mapping requirements for the files and using the new file with the players that are missing mappings with no luck. 

It has happened a few times over the course of multiple seasons.

**Comment by narion** [comment]
"2022-01-12 19:13:07,031 | NewGAN Mapper: 0/1: ['2002888409', 'ENG', None, '3'], Caucasian, None
2022-01-12 19:13:07,032 | NewGAN Mapper: Ethnicity African has no faces left for mapping. Skipping player 2002888409"

**Comment by narion** [comment]
> 

This is despite having "Allow Duplicates" option selected :)

**Comment by Maradonna90** [comment]
I would need the full log and your RTF

**Comment by narion** [comment]
[2029.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7918314/2029.zip)
Attached

**Comment by Maradonna90** [comment]
So there are ESW and MGL are new 3-letter shortcuts that are missing. I can't reproduce your error. Maybe if you give me your XML file.

**Comment by narion** [comment]
[profile.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7919598/profile.zip)
added the cfg files too if that helps, I did recreate the profile as a "just in case" but still received the error afterwards where it seems to be randomly missing. Have also attempted full regeneration & splitting the RTF to smaller chunks with the same results.

**Comment by polygon21** [comment]
I'm having the same issue with 1.3 as well... downgrading to 1.2.1 seems to have fixed it though... i have attached my logfile.. the top portions were my attempts using 1.3, the latest timestamps were from 1.2.1


[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/7920210/newgan.log)

**Comment by polygon21** [comment]
just tried 1.3.1, seems like still having issues with african faces? got many of these in my logs.. 2022-02-22 13:59:22,180 | NewGAN App: Ethnicity African has no faces left for mapping. Skipping player 1919085726
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/8114003/newgan.log)

**Comment by twointum** [comment]
Same issue:
![image](https://user-images.githubusercontent.com/35749928/156497585-1f135bfd-8678-424b-aa3d-bb06a6fbcb15.png)

![image](https://user-images.githubusercontent.com/35749928/156497692-8a40278d-0c60-43c4-a197-0c79dc88d2b6.png)

This is also unexpected, if I have allow dups, it shouln't skip guys:
![image](https://user-images.githubusercontent.com/35749928/156497975-0df7cfc6-801d-4749-9af5-7f3322695fc6.png)

I don't think the allow dups is working.

**Comment by Maradonna90** [comment]
if it doesnt exist it means its not in your config file. Reporting is for reporting bad images in the facepack.

**Comment by narion** [comment]
I have found a work around for this, although does slightly ruin the immersion. 

Deleting the profile used on last update, create new profile, run generation from scratch. My saves in the year 2032 and is 330k+ newgen players. But it does generate with no errors when I do this but have to do these steps or I get the reported errors.
