### ISSUE TITLE
[BUG]Program stuck on preserve

### ISSUE THREAD

**Issue by SpyGunit** [Maradonna90/NewGAN-Manager#112]
I have been using the program for 2 seasons, so i have used generate and preserve again and everything was perfect.
Now i try to do preserve with my new .rtf but the loading bar stucks and the process never ends.
I reinstall everything but the problem still exists.
How can i fix it?

[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/7889113/newgan.log)
![Screenshot 2022-01-18 143637](https://user-images.githubusercontent.com/95938322/149939265-7a095b6e-537e-4c54-8483-90723dccffc5.png)

**Comment by SpyGunit** [comment]
https://file.io/wqBZxa3UFwry my .rtf file

**Comment by Maradonna90** [comment]
please use 'English' as ingame language for exporting the RTF

**Comment by SpyGunit** [comment]
https://file.io/aIV4ANKcuVOk my english .rtf

**Comment by Neilj71** [comment]
I'm also seeing this issue, english is ingame language[language[](url)](url)
[2023.rtf.zip](https://github.com/Maradonna90/NewGAN-Manager/files/10123861/2023.rtf.zip)
[newgan copy.log.zip](https://github.com/Maradonna90/NewGAN-Manager/files/10123866/newgan.copy.log.zip)

newgan.log attached too - hangs at preserve but when running generate works fine
