### ISSUE TITLE
Football Manager not exporting the right RTF file format. [BUG]

### ISSUE THREAD

**Issue by Giniius** [Maradonna90/NewGAN-Manager#113]
**Describe the bug**
When exporting RTF file, there are discrepancies that do not allow for NewGan Manager to work. Two RTF files are created in the same way, with the only difference being the date on which they were created. The earlier RTF file works without issue, the newer RTF file does not produce the generated faces. When analyzing the issue, I have noticed that the working RTF file is different in that it has the 3 letter abbreviation of the nations, while the later not working RTF file does not and I assume this is the reason why the faces do not replace with NewGan Manager despite being created in the exact same way. I have tried re-installing NewGan, as well as the views, and cannot generate an RTF file that includes the 3 letter abbreviation of the players nationalities, which creates issues as Newgan cannot find the right mapping for the player without it. 

**To Reproduce**
1. Create RTF file via the script faces view and is newgen filter by pressing CTRL + A then CTRL + P and exporting as text file. 
2. Inspect RTF file through word

**Expected behavior**
RTF file has the right mapping via 3 letter abbreviation. 

**Screenshots**
Working RTF File
![image](https://user-images.githubusercontent.com/96626613/150215081-74f5a5f8-e824-4dde-8da0-5957c6ed4622.png)
Subsequent RTF Files
![image](https://user-images.githubusercontent.com/96626613/150215184-28baf286-c68c-4460-aa31-a33aa4f981df.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
**Attachments**
Add your `newgan.log` and RTF-File

**Comment by forkloppsake97** [comment]
I have the exact same issue

**Comment by forkloppsake97** [comment]
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/8126556/newgan.log)
[July 2023.rtf.pdf](https://github.com/Maradonna90/NewGAN-Manager/files/8126576/July.2023.rtf.pdf)

**Comment by kbensel** [comment]
Mine has never worked properly because of this issue, in both version 1.3.0 and 1.3.1.

**Comment by DannyOwers** [comment]
is there a solution to this as i am suffering from the same issue?

**Comment by moehrem** [comment]
It doesnt seem to be an issue of NewGAN. I had the same problem and recognized a difference in the given information between the standard skin and my 3rd party skin: The standard skin shows the nations flag AND the nations 3-letter abbreviation. My 3rd party skin does show the flag only.

Could solve it this way:
- Reset the Skin to the "Football Manager" standard skin
- restart the game
- open player search with custom filter and view from NewGAN
- check, if its not just the flag shown in the nations column, **but also the short term / 3 letters nations abbreviation**
- all the rest as per instructions: export, use NewGAN-Manager, enjoy new faces

Thereafter you may rechange your skin as you wish.

**Comment by kbensel** [comment]
> Kind of a repost, as I said it in #136 already: It doesnt seem to be an issue of NewGAN. I had the same problem and recognized a difference in the given information between the standard skin and my 3rd party skin: The standard skin shows the nations flag AND the nations 3-letter abbreviation. My 3rd party skin does show the flag only.
> 
> Could solve it this way:
> 
> * Reset the Skin to the "Football Manager" standard skin
> * restart the game
> * open player search with custom filter and view from NewGAN
> * check, if its not just the flag shown in the nations column, **but also the short term / 3 letters nations abbreviation**
> * all the rest as per instructions: export, use NewGAN-Manager, enjoy new faces
> 
> Thereafter you may rechange your skin as you wish.

I can confirm that this works.

I tried it long ago and for some reason it didn't work (likely user error), but tried it again yesterday and it worked properly.

**Comment by forkloppsake97** [comment]
@kbensel Thank you! I've been trying to fix it for months and now it works

**Comment by Dewanggaarga** [comment]
your information is really useful
