### ISSUE TITLE
[BUG] NewGAN is unable to start without internet connection

### ISSUE THREAD

**Issue by edwin** [Maradonna90/NewGAN-Manager#121]
**Describe the bug**
It seems that NewGAN is checking for new version everytime it is started, so cannot work at all when offline.

**To Reproduce**
1. Disable internet connection
2. Start NewGAN

**Expected behavior**
Application is able to run smoothly despite in offline condition

**Desktop (please complete the following information):**
 - OS: Win 10

**Comment by Maradonna90** [comment]
have you tried the latest release? It should fix the issue.
