### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by chriscc88** [Maradonna90/NewGAN-Manager#125]
Wont let me open the application, foolowed the instructions and have installed and reinstalled but didnt work, also tried via terminal but when i click open anyway/open nothing appears and just the message saying open doesnt appear

**Comment by stckhlm73** [comment]
Same.

**Comment by chuchunyang1988** [comment]
I am having the exact same issue.

**Comment by stckhlm73** [comment]
No update? Is this app  dead?

**Comment by chuchunyang** [comment]
Guys I found the solution from another post here. We simply need to enable Rosetta for this app by right clicking -> Get Info, and then tick the "Open using Rosetta" box.
