### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ShabbaBrenks** [Maradonna90/NewGAN-Manager#129]
**Describe the bug**
My NEW GAN app doesn't start up (NewGAN-Manager-Installer-Win-v1.3.1). The first time it did, but then there where some players who didn't have the new regen faces. Since then, it never started when I need it during installation.

**Comment by gamecufc** [comment]
Having the same issue. App wont load.

**Comment by Maradonna90** [comment]
dupliacte to #130

**Comment by jespu** [comment]
Did you find a fix? It doesn't open for me either.
