### ISSUE TITLE
NewGAN - Manager will not open.

### ISSUE THREAD

**Issue by tayrwilson** [Maradonna90/NewGAN-Manager#130]
Cannot get the app to open on Windows.

I recently switched from FM21 to FM22, and had zero issues with the program before. I have tried every version from 1.2.1 to 1.3.1, I have restarted my computer, I have deleted every single file related to the program, redownloaded, etc.

The application installs with no problem, but nothing will happen when attempting to open the program. The cursor will change for a brief moment to loading, but nothing further.

**Comment by tayrwilson** [comment]
Repairing the file states: "The item 'pythonw.exe' that this function refers to has been changed for moved, so this shortcut will no longer work properly."

It eventually comes up a match that I can use to fix it, or delete it. This shows up on every install, and the fix never works.

**Comment by gamecufc** [comment]
Same issue, app wont load

**Comment by jespu** [comment]
Did you find a fix? It seems the people in charge of this program have no interest in helping.

**Comment by tayrwilson** [comment]
> Did you find a fix? It seems the people in charge of this program have no interest in helping.

I gave up and stopped trying for about a week. When I eventually tried again it opener without issue, but has not worked since so I've given up.

**Comment by jespu** [comment]
> 

i actually got it to work. you have to fully delete the manager files from your hidden user data and then download the newest version again. look the hidden files part up on google, its in the program section

**Comment by das-peterj** [comment]
> > 
> 
> i actually got it to work. you have to fully delete the manager files from your hidden user data and then download the newest version again. look the hidden files part up on google, its in the program section

@jespu Could you elaborate on this? I'm a new FM player and was looking to spice up my regens but I can't get the program to open on Windows.
