### ISSUE TITLE
Doesn't work since the last game update (22.4.0)

### ISSUE THREAD

**Issue by ecbjo** [Maradonna90/NewGAN-Manager#134]
Since the last game update, 22.4.0, the NewGAN manager doesn't work. There are no error messages or anything like that, faces just don't get applied to new players anymore. Have tried the classic clearing of cache and that but to no success.

**Comment by Smithin8or** [comment]
I too am having this problem, I tried just regenerating all faces from last season and it has only removed them.

**Comment by heitoormartins** [comment]
same thing here

**Comment by tomolom** [comment]
same issue for me - log is full with "NewGAN Mapper: Mapping for  is missing. Skipping player 2002319411" etc

**Comment by ecbjo** [comment]
@tomolom Exactly, saw that in the log as well!

**Comment by heitoormartins** [comment]
Any solution?

**Comment by Maradonna90** [comment]
Are you using the english (UK) as ingame language when exporting the RTF? Country Codes differ depending on the ingame language.

**Comment by ecbjo** [comment]
@Maradonna90 No, I'm using my first language, Swedish in my case. Never switched or changed it.

**Comment by Maradonna90** [comment]
Use English (UK) then.

**Comment by Manningham** [comment]
> Use English (UK) then.

Is this a firm requirement? I feel like it should be called out in the README.md, then, at least. I have been experiencing inconsistent mappings (similar to #111) over two versions of the tool since last summer - just changed my in-game language to English (UK), re-generated images using "overwrite" (which changes all the faces, sadly) and now seem to have generated portraits for all of my players.

**Comment by ecbjo** [comment]
> Use English (UK) then.

But I've used Swedish successfully and mapped new faces up until the 22.4.0 version of the game. After that nothing works.

**Comment by heitoormartins** [comment]
Tried used English UK, but I got the same result in the end, no faces at all

**Comment by Maradonna90** [comment]
cant really say without logs and config fles.
