### ISSUE TITLE
Nationalities do not import from FM into RTF File [BUG]

### ISSUE THREAD

**Issue by daarsc** [Maradonna90/NewGAN-Manager#136]
**Describe the bug**
somehow i can't get NewGan to work anymore and i'm pretty sure its because the nationalities don't get imported at all into the RTF file. I tried alot of stuff with the view *SCRIPT FACES player search* but nothing seems to work.. anyone else has the same problem? and maybe knows how to fix it?

![image](https://user-images.githubusercontent.com/103514145/162978359-24da3e88-7e6f-4182-b875-69c30a64d396.png)
as you can see the NAT and 2nd NAT tab are just completely empty.

**Comment by moehrem** [comment]
It doesnt seem to be an issue of NewGAN. I had the same problem and recognized a difference in the given information between the standard skin and my 3rd party skin: The standard skin shows the nations flag AND the nations 3-letter abbreviation. My 3rd party skin does show the flag only.

Could solve it this way:
- Reset the Skin to the "Football Manager" standard skin
- restart the game
- open player search with custom filter and view from NewGAN
- check, if its not just the flag shown in the nations column, **but also the short term / 3 letters nations abbreviation**
- all the rest as per instructions: export, use NewGAN-Manager, enjoy new faces

Thereafter you may rechange your skin as you wish.
