### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SimpsonFanOnGitHub** [Maradonna90/NewGAN-Manager#138]
**Describe the bug**
*EDIT* (forgot descr.) The manager doesn't download.

**To Reproduce**
1. Go to '[...](https://github.com/Maradonna90/NewGAN-Manager/releases/tag/v1.3.1)'
2. Click on '[NewGAN-Manager-Installer-Win-v1.3.1.zip](https://github.com/Maradonna90/NewGAN-Manager/releases/download/v1.3.1/NewGAN-Manager-Installer-Win-v1.3.1.zip)'
3. Run the installer

**Expected behavior**
I expected there to be the normal menu instead of the WIzard going straight to finish.

**Screenshots**
![NEWGAN](https://user-images.githubusercontent.com/69220647/163436573-33554359-478b-43e8-919f-34969876214d.PNG)

It downloads for a bit and then goes to this screen, but the NewGAN-Manager is not installed..

**Desktop (please complete the following information):**
 - OS: Windows

**Attachments**
None.

**Comment by jespu** [comment]
I'm having this exact issue now, did you find a solution?

**Comment by Maradonna90** [comment]
no idea. framework issue.
