### ISSUE TITLE
[BUG] Manager won't install anymore

### ISSUE THREAD

**Issue by jespu** [Maradonna90/NewGAN-Manager#140]
I install the new gan manager wizard as instructed, but when it's time for the installer to install the program, it speeds through and prompts me to click finish. When I click it, it hasn't downloaded anything for me. It keeps doing this no matter how many times i reinstall the installer program.

I'm on windows 10, and I already had the whole program before, but it didn't work in the game so I reinstalled it. Then at one point it didn't even let me open it anymore. Now, after another delete and reinstall attempt, it wont even install the program. I'm not sure if this is a problem with me, my computer or the program.

**Comment by jespu** [comment]
I somehow got it installed now from an old installer in my file, but the application wont open...

**Comment by lfcdk11** [comment]
exact same issue happening to me, have you managed to fix it?
