### ISSUE TITLE
[BUG] Newgan manager app won't open

### ISSUE THREAD

**Issue by jespu** [Maradonna90/NewGAN-Manager#141]
After downloading the manager according to the instructions, it wont open. It doesn't display an error message or anything, it just doesnt open by double-clicking, from the taskbar or from anywhere else.

1. Download any version of the manager
2. Attempt to open it
3. See error (well, it doesn't display one.)

Expected behavior
I expected it to open as it should.

I'm on pc windows 10

**Comment by Maradonna90** [comment]
duplicate #130
