### ISSUE TITLE
newgan manager wont open

### ISSUE THREAD

**Issue by conway9** [Maradonna90/NewGAN-Manager#142]
i had it working but now it wont open at all for some reason

**Comment by johancantona** [comment]
same here

**Comment by badboyz08** [comment]
me too

**Comment by Nabil0385** [comment]
moi aussi heeelp :(

**Comment by badboyz08** [comment]
guys i solve it
you guys need to uninstall program completely
i use program call revo uninstall and remove all register stuff like that

**Comment by Nabil0385** [comment]
super ça fonctionne :) merci badboyz08 tu est génial
