### ISSUE TITLE
when I choose generate faces it says 'folder seasian is missing in the image directory' pls help

### ISSUE THREAD

**Issue by olliedwards20** [Maradonna90/NewGAN-Manager#144]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Attachments**
Add your `newgan.log` and RTF-File

**Comment by Ayal1** [comment]
It seems like you didn't extract the entirety of the NewGAN Facepack, are all the folders there? There should be 14 different folder filled with faces inside the facepack's folder.

**Comment by vinx8otto** [comment]
i have the same problem, i've re-downloaded all the packs, but it's the same message, it's missing the seasian folder in the image directory.
