### ISSUE TITLE
Shown "Can't be opened" on MacOS after installation.

### ISSUE THREAD

**Issue by aidanchangg** [Maradonna90/NewGAN-Manager#145]
When I opened the application in the application folder or the installation folder, it says "The application "NewGAN-Manager" can't be opened, sometimes it shows up this message + a open app pop-up, but still, doesn't open up the application. This is a big bug and please fix this asap.

**Comment by kaharlykskyi** [comment]
Same story on Mac.
macOS Monterey 12.6

**Comment by j4r3kb** [comment]
Go to the Applications folder, right-click the app and select Open?
