### ISSUE TITLE
[BUG] Certain lengths of player UIMs considered invalid

### ISSUE THREAD

**Issue by Manchae** [Maradonna90/NewGAN-Manager#151]
**Describe the bug**
I encountered an odd issue today when trying to give a face to a single "silhouette player" that i'd just signed (something that i've successfully done before) where I was getting the invalid RTF file error when it was being parsed.

After having a play around to try and fix it and running a few tests, I think it came down to the fact that the player's UIM was only 6 digits long (it could affect other lengths of UIM too, i've not tested this, only my example where it was length 6):
![image](https://user-images.githubusercontent.com/119763594/205464120-b66eb50f-ff2c-45cc-9d10-304905ca293d.png)
![image](https://user-images.githubusercontent.com/119763594/205464550-60bea458-317e-4d84-b366-68b784662028.png)

I ran another test where I tried a Preserve run using an [RTF file containing this player (A) and one other player (B)](https://github.com/Maradonna90/NewGAN-Manager/files/10147474/DerbySquad2.1.rtf.zip) and, whilst that run "completed", I noticed that player A (with the 6-length UIM) was still just a silhouette and the logs seem to suggest that their line in the RTF file was ignored and only player B's line was processed:

  _2022-12-03 21:51:38,656 | NewGAN App: Start Replace Faces
  2022-12-03 21:51:38,656 | NewGAN App: rtf: C:\Users\Mike\Documents\Sports Interactive\Football Manager 2023\newgan outputs\DerbySquad2.1.rtf
  2022-12-03 21:51:38,656 | NewGAN App: img_dir: C:\Users\Mike\Documents\Sports Interactive\Football Manager 2023\graphics\faces/
  2022-12-03 21:51:38,657 | NewGAN App: profile: FM23Derby
  2022-12-03 21:51:38,657 | NewGAN App: mode: Preserve
  2022-12-03 21:51:40,640 | NewGAN App: 0/1: ['28066818', 'ENG', None, '0'], Caucasian, None
  2022-12-03 21:51:41,176 | NewGAN App: Info window: Finished! :)_

**To Reproduce**
1. Create RTF file from a script faces view where one or more players has a UIM of length 6
2. Do a replace faces run in NewGAN-Manager using that RTF file
3. Any lines for players with a UIM of length 6 are skipped, or if the RTF file contains ONLY players with UIMs of length 6 then an invalid RTF file error is thrown

**Expected behavior**
Able to replace faces of players with a UIM of length 6

**Attachments**
[DerbySquad2.1.rtf.zip](https://github.com/Maradonna90/NewGAN-Manager/files/10147474/DerbySquad2.1.rtf.zip)

**Comment by Ayal1** [comment]
Not a bug, this is intentional. That player, Riquelme, is a real player and as most real players, has a UID that is much shorter (or smaller value) than newgen UIDs. In order to not create conflicts with other facepacks, newgan manager only assigns faces to UIDs that are above a certain value so that only newgens should be getting assigned faces.

**Comment by Manchae** [comment]
Ah I see, thanks for the info and apologies for the false report.
