### ISSUE TITLE
[BUG] Newgan fails to open on Manjaro Linux

### ISSUE THREAD

**Issue by Ricardeano** [Maradonna90/NewGAN-Manager#152]
**Describe the bug**
NewGAN 1.3.1 fails to start on Manjaro linux following installation

**To Reproduce**
1. Install the Appimage
2. Start from the application launcher
3. Nothing happens (no message it failed, and apparently not running in background)
4. (Additionally if I run the appimage without integrating, nothing happens)

**Expected behavior**
For the app window to open.

**Screenshots**
Nothing happens so I won't include anything, but if there is anything that will help let me know.

**Desktop (please complete the following information):**
 - OS: Manjaro (5.15.81-1-Manjaro)
 - Graphics driver: Nvidia 525.60.11

**Attachments**
I don't think a log file is being created. I checked in the applications folder (where the appimage was integrated) and also ran the original file (before integration) and there was no log file created in either folder.

**Comment by jaydubem** [comment]
Getting the same problem with Arch on plasma, nothing happens after trying to run, despite making executable

**Comment by Lds502** [comment]
Same thing is happening for me when running on Arch. I don't get a log file either but attempting to run the program in the terminal I get the following output:

/tmp/.mount_NewGANZmGrwC/usr/app/xmlparser.py:9: DeprecationWarning: invalid escape sequence \/
  UID_regex = re.compile('([0-9]{7,}(?=\/))')
/tmp/.mount_NewGANZmGrwC/usr/app/xmlparser.py:28: DeprecationWarning: invalid escape sequence \/
  UID_regex = re.compile('('+uid+'(?=\/))')
/tmp/.mount_NewGANZmGrwC/usr/app/rtfparser.py:28: DeprecationWarning: invalid escape sequence \|
  rtf_regex = re.compile('(\|\s*[0-9]{8,}\s*)(\|\s*([A-Z]{3})*\s*)+(\|[\s*\w*\.*\-*]+)(\|[\s*\d+]+){3}\|')
Traceback (most recent call last):
  File "/tmp/.mount_NewGANZmGrwC/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_NewGANZmGrwC/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_NewGANZmGrwC/usr/app/newganmanager/__main__.py", line 4, in <module>
    main().main_loop()
  File "/tmp/.mount_NewGANZmGrwC/usr/app/newganmanager/app.py", line 439, in main
    return NewGANManager()
  File "/tmp/.mount_NewGANZmGrwC/usr/app/newganmanager/app.py", line 41, in __init__
    super().__init__()
  File "/tmp/.mount_NewGANZmGrwC/usr/app_packages/toga/app.py", line 272, in __init__
    self.factory = get_platform_factory(factory)
  File "/tmp/.mount_NewGANZmGrwC/usr/app_packages/toga/platform.py", line 41, in get_platform_factory
    from toga_gtk import factory
  File "/tmp/.mount_NewGANZmGrwC/usr/app_packages/toga_gtk/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/tmp/.mount_NewGANZmGrwC/usr/app_packages/toga_gtk/app.py", line 13, in <module>
    from .keys import gtk_accel
  File "/tmp/.mount_NewGANZmGrwC/usr/app_packages/toga_gtk/keys.py", line 3, in <module>
    from .libs import Gdk
  File "/tmp/.mount_NewGANZmGrwC/usr/app_packages/toga_gtk/libs/__init__.py", line 1, in <module>
    from .gtk import *  # noqa: F401, F403
  File "/tmp/.mount_NewGANZmGrwC/usr/app_packages/toga_gtk/libs/gtk.py", line 1, in <module>
    import gi
  File "/tmp/.mount_NewGANZmGrwC/usr/app_packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full

**Comment by Lds502** [comment]
I got this to run on arch linux.

I extracted the AppImage

./NewGAN-Manager-1.3.1-x86_64_a34ba454bd304ad0d66866f7fb7dab26.AppImage --appimage-extract

This creates a squashfs-root folder.

I deleted the following file:

"/squashfs-root/usr/lib/libgmodule-2.0.so.0"

Then running "/squashfs-root/AppRun" the application launches.

I was getting other errors when trying to run the AppImage after repackaging it, however.

I had to run the application without any themes applied otherwise I was getting GTK errors when trying to select the location of my facepack.

**Comment by keithcrooks** [comment]
> I had to run the application without any themes applied otherwise I was getting GTK errors when trying to select the location of my facepack.

I've followed the first step to get it to launch on SteamOS on Steam Deck in desktop mode.

I'm also getting the GTK errors when trying to select the image dir.

What do you mean by running the app without any themes? How do you do that?

Thank you

**Comment by Lds502** [comment]
Looking at it again, it may be permission errors. I was getting "PermissionError: [Errno 13] Permission denied:"
when trying to open a folder.

running the app as sudo seems to work.

sudo ./AppRun

**Comment by keithcrooks** [comment]
> Looking at it again, it may be permission errors. I was getting "PermissionError: [Errno 13] Permission denied:" when trying to open a folder.
> 
> running the app as sudo seems to work.
> 
> sudo ./AppRun

That worked. Although it sets the config.xml owner as `root:root` and I wasn't sure if that would cause any problems in game so I just changed the owner to `deck:deck`.

Thank you so much for your reply :+1:

**Comment by gleidhold** [comment]
This worked, maybe it should be added to the readme?
