### ISSUE TITLE
'Is newgen' filter and SCRIPT FACES view not showing up in FM23

### ISSUE THREAD

**Issue by adamb17** [Maradonna90/NewGAN-Manager#153]
I can't use the newgen filter or the player search view in fm23 even tough they are in my filters and views files on my mac. I have been able to find a newgen filter on steam workshop but i still can't add NewGan to my game because the player view isn't showing up. Is there anything i can do to fix this or how can i find a different player view that would work

**Comment by Ayal1** [comment]
Are the appropriate filters and views in the FM23 folders? If they're in the FM22 you'll have to navigate to them in-game or move them to the FM23 folders and try again.

**Comment by Maradonna90** [comment]
close due to inactivity.
