### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ballwinningfm** [Maradonna90/NewGAN-Manager#157]
HI! my newgan manager won't open at all on mac 
![Screen Shot 2023-01-18 at 21 42 19](https://user-images.githubusercontent.com/123027637/213302743-d9490850-e063-4e51-b25d-d745bf0957e4.png)

**Comment by Maradonna90** [comment]
no idea, I dont own a Mac for debugging purposes. Seems to be an issue from the framework.
