### ISSUE TITLE
[BUG] XML Parsing error!

### ISSUE THREAD

**Issue by Airwane** [Maradonna90/NewGAN-Manager#158]
all steps are follow on windows until it's time to reload the preferences in FM and then I get this error message.

the only way to close it is to end task in task manager

see attached image
![Screenshot_11](https://user-images.githubusercontent.com/98708419/213861832-4f79cd13-1feb-4049-bddb-e687b806d996.png)

**Comment by Maradonna90** [comment]
nothing to do with NewGan.
