### ISSUE TITLE
[Feature Request] Club-specific kits in Generated Face Pictures

### ISSUE THREAD

**Issue by sergeiwallace** [Maradonna90/NewGAN-Manager#159]
Big fan of the work you guys have done with NewGAN-Manager. Question/feature request, any plans on using ML to extract club kits from player face pictures (from say DF11 facepack) to use them in your generated faces so they are wearing their club-specific kit? Obviously not a trivial feature but I imagine it's possible.

**Comment by Maradonna90** [comment]
not planned, would be super complex and to much work.
