### ISSUE TITLE
[BUG] Mongolia, Kosovo and Eswatini new country codes aren't supported in newer versions of FM

### ISSUE THREAD

**Issue by Ayal1** [Maradonna90/NewGAN-Manager#160]
**Describe the bug**
Mongolian, Kosovan and Emaswati newgens don't get a face assigned by NewGAN Manager in the newer version of FM (FM23 tested).

**To Reproduce**
Try and assign a face to Mongolian, Kosovan and Emaswati newgens (that don't have another applicable ethnicity)

**Expected behavior**
A face gets assigned to said newgens.

My _suggested_ solution:
[cfg.json](https://github.com/Maradonna90/NewGAN-Manager/blob/master/src/newganmanager/.config/cfg.json) should have the following added: `"MGL": "Asian", "KOS": "YugoGreek", "ESW": "African"`

**Comment by Nii-Lamptey** [comment]
Thanks for this - editing the cfg.json to map **KOS** to **YugoGreek** file worked for me.

**Comment by chimzfm** [comment]
Still not having faces for KOS

**Comment by polygon21** [comment]
> **Describe the bug** Mongolian, Kosovan and Emaswati newgens don't get a face assigned by NewGAN Manager in the newer version of FM (FM23 tested).
> 
> **To Reproduce** Try and assign a face to Mongolian, Kosovan and Emaswati newgens (that don't have another applicable ethnicity)
> 
> **Expected behavior** A face gets assigned to said newgens.
> 
> My _suggested_ solution: [cfg.json](https://github.com/Maradonna90/NewGAN-Manager/blob/master/src/newganmanager/.config/cfg.json) should have the following added: `"MGL": "Asian", "KOS": "YugoGreek", "ESW": "African"`

Thanks for this.. managed to add in some nationalities not mapped as well
