### ISSUE TITLE
[BUG] No faces left for mapping (duplicates turned on)

### ISSUE THREAD

**Issue by luucksson** [Maradonna90/NewGAN-Manager#161]
**Problem**
I got the list of newgens, launched NewGAN Manager and I have photos of most newgens. I got youth intake and wanted to have photos for all of them. I make a list of regens in my club (I can clearly see some of the guys in the .rtf file). Launch the program. But nothing changes in the config file and regens don't have faces. FM 2023
Now in log i see that there was no faces left for mapping, and it skipped some players, which I don't understand, because I have duplicates turned on.
**Desktop (please complete the following information):**
 - OS: Windows 11

**Attachments**
Log is too big, github doesn't suppor .rtf.

**Comment by bread22** [comment]
change this file
`%localappdata%\Programs\NewGAN-Manager\app\mapper.py`
comment line 30-31
```python
            for eth in self.eth_map:
                self.eth_map[eth] = self.eth_map[eth] - set(prf_imgs)
```

**Comment by bread22** [comment]
The issue is that `Mapper` class doesn't know whether `duplicates` is allowed
