### ISSUE TITLE
Installer cannot be opened on Mac!

### ISSUE THREAD

**Issue by MaxMunch** [Maradonna90/NewGAN-Manager#162]
The installer is straight up not opening after unpacking it on Mac. Error notification comes in that the app cannot be opened! 

Please replace the folder with a working version for Mac users.

**Comment by jleviminzi** [comment]
In case helpful, further to Max's comment, the unidentified developer issue -> workaround is not an issue here. The app itself just won't open even after developer permission. 
<img width="261" alt="Screenshot 2023-02-25 at 7 33 40 PM" src="https://user-images.githubusercontent.com/121972442/221385971-224bf0b6-bb2c-43d0-9135-ad4c994d768c.png">

**Comment by oclark44** [comment]
Im having the same issue

**Comment by brankfrank** [comment]
This worked for me https://support.apple.com/en-us/HT211861

**Comment by jmb83** [comment]
Right click on the app>get information > Mark the option "open with rosetta"
