### ISSUE TITLE
[Refactor] Potential refactor

### ISSUE THREAD

**Issue by imfulee** [Maradonna90/NewGAN-Manager#176]
Hey there!

I am currently using Linux and I've noticed the Linux build is broken for a long time. Therefore, I'm potentially rewriting parts of it to make the build process a bit better cross platform. Is it possible to know on `src/rtfparser.py` line 23, what `data_fields[7]` is?

Also, may I ask how did you create a `.fmf` view file with the skin tone as a column?

Thank you for your work and countless others!

**Comment by Maradonna90** [comment]
View comes from skinning. you can bake in views if you edit skin files. than you can export this baked in view. tada.

Should be the ethnicity value from FM.
