### ISSUE TITLE
[BUG] prf_imgs.remove accidentally messing with 'preserve' and 'overwrite' mode ?

### ISSUE THREAD

**Issue by guiseiz** [Maradonna90/NewGAN-Manager#179]
there might be an issue in the logic that can cause the duplicates to not work as intended. The problem lies in the generate_mapping method when the mode is set to "Preserve" or "Overwrite".

In the code block where it checks for duplicates and removes images from the `prf_imgs` list, there is a line that can inadvertently shorten the selection pool of images for ethnicities:

```prf_imgs.remove(xml_data[player[0]]["image"])```

This line attempts to remove an image from `prf_imgs` based on the player's ID. However, if the same image is used for multiple players, removing it once will reduce the available selection pool for subsequent players with the same ethnicity. This unintended removal can result in duplicates not being allowed effectively.

this might be the culprit behind the '_...has no faces left for mapping. Skipping player_' issue

**Comment by Maradonna90** [comment]
no it essentially remove images from the profile, so images that are already used.
