### ISSUE TITLE
MacOs Ventura cant open the file,even if open the Any Resource Button[BUG]

### ISSUE THREAD

**Issue by sunrise1998** [Maradonna90/NewGAN-Manager#180]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Attachments**
Add your `newgan.log` and RTF-File

**Comment by chenfanghang** [comment]
Go to the macOs folder and run sudo./NewGAN-Manager on the terminal
