### ISSUE TITLE
[BUG] is newgen filter don't show all the new players

### ISSUE THREAD

**Issue by errore404-it** [Maradonna90/NewGAN-Manager#181]
**Describe the bug**
Imported the filter "is newgen search filter.fmf" from the 1.3.1 version of the program. Applying the filter it shows all the players with the UID beginning with "2002" (length 10 characters) and not the ones starting with "2000" (still 10 characters), still newgen players.

**To Reproduce**
I don't know, start a new game with FM23 (game version 23.5.0+1827095 - m.e v23.2.0.0) and a lot of leagues to play with. Database is around 301.000 players.

**Expected behavior**
All the newgen players should have a face.

**Screenshots**
Useless to give you a screenshot,

**Desktop (please complete the following information):**
 - OS: Win11

**Attachments**
Useless to add `newgan.log` file since the program "per se" is working fine, ans also the RTF file is generated correctly, with all the players extracted from the filter. The problem is the filter itself.

**Notes**
All the players listed as UID beginning with "2000" are for sure newgen but they do not have the "original FM ugly face"... they have no face at all... maybe the game is not flagging them as "new gen" even if they are?

**Comment by Maradonna90** [comment]
this is more an issuje with FM then. Cant do anything about working filter options ingame. In doubt create your own filter ingame and sees if its persists.
