### ISSUE TITLE
Regens got the ids changed with Patch 24.2.0

### ISSUE THREAD

**Issue by dpendao** [Maradonna90/NewGAN-Manager#186]
My regens got the ids changed with Patch 24.2.0 and now I can't use newgan manager because it uses the ids without the "r-" ... I don't understand the intention of ruining what users do to create a more immersive game.

**Comment by BassyBoyYT** [comment]
Real players and newgens were actually starting to use the same id's. It's a new way where SI can keep adding people to the database without messing with the newgens :)

**Comment by dpendao** [comment]
Thanks for the answer. Any ideas to solve it?

**Comment by BassyBoyYT** [comment]
Well you can assign the r- in the config file, but for 20k plus players that's madness. I'd say wait until this has been adjusted within the NewGAN manager to re-run it all. I don't know how long it'll take so here's hoping it's gonna be fixed soon 😄
