### ISSUE TITLE
[BUG] Some faces in SAMED, ASIA, AMERICA, etc won't show

### ISSUE THREAD

**Issue by cloverjojo** [Maradonna90/NewGAN-Manager#193]
I found some codes in xml file:
"<record from="South American/Asian596" to="graphics/pictures/person/r-2002075998/portrait"/>"
wrong file location is directed.

This causes the player face not showing.
![1](https://github.com/Maradonna90/NewGAN-Manager/assets/44335822/92758966-8aaf-4e35-b2e5-d88c21c1f566)
![2](https://github.com/Maradonna90/NewGAN-Manager/assets/44335822/89184043-f071-475a-8c55-6c570fe6deab)
![3](https://github.com/Maradonna90/NewGAN-Manager/assets/44335822/48271751-6997-4fed-a2ea-125348e0b8ce)

Is there any solution to this?

**Comment by Maradonna90** [comment]
the xml config is wrong it references to "South American/African*" which clearly doesnt exist. Dont know how that happened.

**Comment by 034georgie** [comment]
Hi @Maradonna90 - wanted to flag that this seems to be only happening when using the preserve function.

**Comment by fikaaydin** [comment]
hello there is problem like that i will upload my newgan.lof file and it says some maps are missing.
![Ekran görüntüsü 2023-12-15 113501](https://github.com/Maradonna90/NewGAN-Manager/assets/151656885/51edfcfa-94f3-4f1f-b6b2-0dc9a9081c26)

**Comment by jwinther95** [comment]
This seems to be an issue with 2 nationalities. I just looked into my RTF file and went through some of my regens that are missing pictures. In all cases it was 2 nationalities, e.g. "GER/ECU" and corresponding to that inside the config.xml: "African/Central European1234". Another example "GER/KAZ" in the RTF, "Seasian/Central European1234" inside the config.xml. Never happened to me in FM23...

**Comment by jwinther95** [comment]
Could it be that it has something to do with how the RTF is formatted. Look at this comparison from FM23 and FM24. There seems to be more characters in the new FM24 RTF file (see screenshot)

![grafik](https://github.com/Maradonna90/NewGAN-Manager/assets/64532570/46bc52ee-417f-4f8e-ab7f-c5c38e6589a4)

**Comment by Ayal1** [comment]
> Could it be that it has something to do with how the RTF is formatted. Look at this comparison from FM23 and FM24. There seems to be more characters in the new FM24 RTF file. Also the names of the columns have changed. (see screenshots)
> 
> Can't be a major issue since most faces are working, only double nationalities seem to be affected.
> 
> @Maradonna90
> 
> ![grafik](https://private-user-images.githubusercontent.com/64532570/290908214-46bc52ee-417f-4f8e-ab7f-c5c38e6589a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NzEyMTcsIm5iZiI6MTcwMjY3MDkxNywicGF0aCI6Ii82NDUzMjU3MC8yOTA5MDgyMTQtNDZiYzUyZWUtNDE3Zi00ZjhlLWFiN2YtYzVjMzhlNjU4OWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDIwMDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZTYxNTkxODEzZWM1N2U2Zjg4ODA0MjIyN2U0YzdmNzhjNTk4YzYyNWY0NTQ1MTlkOTMzNzUyNGFkNWI1NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6vcDd7JYltpvDKfU_iUzuajCaAxh1UglHPmBUJlGk-M)
> 
> ![grafik](https://private-user-images.githubusercontent.com/64532570/290908875-c14c803b-9aea-406c-89a8-c967b938ec03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NzEyMTcsIm5iZiI6MTcwMjY3MDkxNywicGF0aCI6Ii82NDUzMjU3MC8yOTA5MDg4NzUtYzE0YzgwM2ItOWFlYS00MDZjLTg5YTgtYzk2N2I5MzhlYzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDIwMDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZGRhNWEwMmM5OTBiMGYyODRiZWJiNDdiNzYwNzMyM2M3ZjRhZDE3M2QzODcwZmM2ODkzZTNiNzEzZWY3NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DczeMPgL3HQfVkfkbAcolNxAyIcevGm2d130Wko4GeQ)

Looks like you're using the wrong view from FM23, there should only be 3 number values to the right, not 4

**Comment by fikaaydin** [comment]
How can find right view for fm 24? Is there a link?

Akif AYDIN
Department of Public Administration
Canakkale Onsekiz Mart University
GSM +905445201527
***@***.***


15 Ara 2023 Cum, saat 23:15 tarihinde Ayal ***@***.***> şunu
yazdı:

**Comment by Ayal1** [comment]
@fikaaydin the view from FM23 is possible to import into FM24 I believe, and it comes with the installer for NewGAN. If you use the latest version of Zealand skin (either for FM23 or FM24) it's built in to the scouting page views.

**Comment by jwinther95** [comment]
I am pretty sure I copied the exact same view from FM23 to FM24 - have to check that again later though... So the view from FM24 looks exactly the same length / content wise as the one from FM23 (see my first screenshot) for you?

**Comment by fikaaydin** [comment]
The main problem is config file actually. In the rtf file I can see the ids but when it becomes config file it doesn’t do some ids in config file. I will make SS for you.( 5 minutes later I will be at home)

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
Gönderen: Jannik W. ***@***.***>
Gönderildi: Saturday, December 16, 2023 12:05:07 AM
Kime: Maradonna90/NewGAN-Manager ***@***.***>
Bilgi: fikaaydin ***@***.***>; Mention ***@***.***>
Konu: Re: [Maradonna90/NewGAN-Manager] [BUG] Some faces in SAMED, ASIA, AMERICA, etc won't show (Issue #193)


I am pretty sure I copied the exact same view from FM23 to FM24 - have to check that again later though... So the view from FM24 looks exactly the same length / content wise as the one from FM23 (see my first screenshot) for you?

**Comment by fikaaydin** [comment]
![config file ID couldnt find SS](https://github.com/Maradonna90/NewGAN-Manager/assets/151656885/c34e3b4a-d830-47a7-8f49-5d1a7e68c2ce)
![trial SS RTF](https://github.com/Maradonna90/NewGAN-Manager/assets/151656885/fb8d53c4-751b-42a4-948b-105ee75f32c4)

**Comment by jwinther95** [comment]
@fikaaydin I am pretty sure thats an issue with the "ultra realistic face pack" - it probably doesn't have enough faces if you don't activate "allow duplicates". Just tried it with the same face pack you are using and I have the same issue (I am on season 7, so I might have more regens in my game than you, but there really aren't a whole lot of files in the face pack you used, assuming you are loading more than 1-4 playable leagues). You could check the Newgan.log (probably located here: X:\Users\<User>\AppData\Local\Programs\NewGAN-Manager\app\newganmanager) - if there are a lot of entries saying "Ethnicity "XYZ" has no faces left for mapping", it's the face pack.

**Comment by Ryok82** [comment]
I´m also having the issue with wrong mapping of some faces. Started happening in FM 24, were not an issue in FM23.
I use the exact same view when generating the .rtf

**Comment by fikaaydin** [comment]
where i look my newgan.log file i have lots of maps are missing. Is there solution when i paying 23 it was ok. but in fm 24
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/13699202/newgan.log)

**Comment by Ayal1** [comment]
@fikaaydin is your game and data language set to English? If not, the 3 letter country codes won't be correct for NewGAN Manager to assign the appropriate ethnicity.

**Comment by fikaaydin** [comment]
I will try in English this time

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
Gönderen: Ayal ***@***.***>
Gönderildi: Monday, December 18, 2023 9:58:10 PM
Kime: Maradonna90/NewGAN-Manager ***@***.***>
Bilgi: fikaaydin ***@***.***>; Mention ***@***.***>
Konu: Re: [Maradonna90/NewGAN-Manager] [BUG] Some faces in SAMED, ASIA, AMERICA, etc won't show (Issue #193)


@fikaaydin<https://github.com/fikaaydin> is your game and data language set to English? If not, the 3 letter country codes won't be correct for NewGAN Manager to assign the appropriate ethnicity.

**Comment by Maradonna90** [comment]
My suspicion is a known bug, where a player decides for a national team that before was his second nation. Then suddenly the nations swap places. I think this might be the case for this issue.

Antonio Carlos Takashiki was probably Japanese at first, then something happened and he changed his first nation to Brazil. At least thats what I assume.
