### ISSUE TITLE
[BUG] NewGAN Manager not opening.

### ISSUE THREAD

**Issue by Kayjay-1** [Maradonna90/NewGAN-Manager#194]
**Describe the bug**
Recently all the faces went away on their own, i did not move any files, i did move my faces file from fm23 to fm24 and i just followed the steps and it worked. But all the faces randomly went from the game i began to uninstall the face pack, newgan manager, and even tried to re-apply the steps of adding the faces. Nothing worked, and now faces aren't in game and newGAN manager won't open no matter what i do.

**To Reproduce**
1. Uninstalled facepack, newgan manager and newgan folder including views and filters
2. Reinstalled facepack folder, newgan manager
3. followed exact steps to apply faces
4. Faces not uploading into fm24 to replace regen faces, and Newgan manager no longer opens.

**Expected behavior**
Newgan manager to open as usual and for faces to upload into the game.

**Desktop (please complete the following information):**
 - OS: Windows 11 [Home]

**Attachments**
Add your `newgan.log` (I dont know where this is/ cannot find it) and RTF-File (Github won't let me upload it)

**Comment by swealam** [comment]
face same issue here with win 11

**Comment by pbootsma519** [comment]
I was able to fix it by deleting the NewGan folder in `%localappdata%\Programs\NewGAN-Manager\` and then uninstalling and re-installing the program.

**Comment by Juliano223** [comment]
> I was able to fix it by deleting the NewGan folder in `%localappdata%\Programs\NewGAN-Manager\` and then uninstalling and re-installing the program.

That worked for me too, you can follow the instructions in this video https://www.youtube.com/watch?v=oZTf0vf2pkY if you don't know how to find the NewGan folder.

**Comment by Kayjay-1** [comment]
Thank you so much guys. Respect. Will give it a go!
