### ISSUE TITLE
Faces dont load ingame [BUG]

### ISSUE THREAD

**Issue by mxltx13** [Maradonna90/NewGAN-Manager#196]
**Describe the bug**
After generating the faces in the newgan manager and reloading the images in the game the players still dont have real faces. I tried multiple rtf files I also did download the faces again to ensure it has nothing to do with them so I running out of Ideas what could be the problem so i wanted to ask here if you have an idea what the problem could be.

**Attachments**
Add your `newgan.log` and RTF-File
[newgan.log+rtf.zip](https://github.com/Maradonna90/NewGAN-Manager/files/13678448/newgan.log%2Brtf.zip)

**Comment by Maradonna90** [comment]
#186 probably
