### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brankfrank** [Maradonna90/NewGAN-Manager#199]
unable to open an unrendered rtf file on MacOS. The rtf files are viewable within textedit, but they are fully formatted. And given the most recent need to find and replace data to fix the r- issue, this makes this unusable.

**Comment by Ayal1** [comment]
Is NewGAN Manager not reading the RTF file? Or are you saying you want to change the UIDs to not have the r- in front first and then run it? Because if the latter is the case, just run it with the RTF file and remove the r- in the generated config instead.

**Comment by Maradonna90** [comment]
I dont understand the bug here. your should not open the RTF file to do the r- workaround. you should open the config.xml for this.
