### ISSUE TITLE
Mappings getting overwritten in Preserve mode

### ISSUE THREAD

**Issue by jonapoul** [Maradonna90/NewGAN-Manager#20]
So I'm trying to generate mappings from two sources:
- my squad,
- player search via scouting menu.

To do this, I've got a profile set up for each, each one reading from a separate RTF file. To start, I run Generate mode on the first profile (squad). I test it in FM, all good. I then run Preserve mode on the second profile, under the assumption that it will append new mappings onto the previous ones without deleting anything. No dice. The squad mappings are gone from `config.xml`, entirely replaced by the player search ones.

As a result, my squad regens now have the crappy 3D models and only those players from the "player search" RTF files have nice new AI faces.

Is this a known issue? I've attached the two config files and the log, in case they're useful at all.

[not_preserved.zip](https://github.com/Maradonna90/NewGAN-Manager/files/5612015/not_preserved.zip)

**Comment by Maradonna90** [comment]
It is known and hopefully fixed with the tests I introduced today. I'll keep that open for now

**Comment by Maradonna90** [comment]
test on all platforms show that this is fixed.
