### ISSUE TITLE
[BUG] Regions and Code

### ISSUE THREAD

**Issue by Freddyzo777** [Maradonna90/NewGAN-Manager#203]
Some of the regions are listed wrong. For example the American Samoa is listed as African in the cfg.json file.
In the mapper.py we have a code saying :
"  if player[3] == "1":
 if "Scandinavian" in [n1_ethnic, n2_ethnic]:
                    p_ethnic = "South American"
                if "Seasian" in [n1_ethnic, n2_ethnic]:
                    p_ethnic = "South American"
                if "Central European" in [n1_ethnic, n2_ethnic]:"

Doesn't that mean if the number is 1, and the ethnic is Scandinavian, it should output South American ?
And Seasian becomes South American if the number is 1?
Shouldn't it be Scandinavian and Scandinavian etc.?
(just like it is in EECA)

Next elif player[3] in ["3", "6", "7", "8", "9"]:
 if "SAMed" == n1_ethnic and player[3] == "7":
                    p_ethnic = "SAMed"
                # South American with 7 is light-skinned
                elif "South American" == n1_ethnic and player[3] == "7":
                    p_ethnic = "South American"
                else:
                    p_ethnic = "African"

If the number in player 3, is either 3, 6, 7 or 9 it should do something. And here we say if it is SAMed and 7, output SAMed. But nothing about number 3, 6, 8 or 9. So it will do those numbers as African?
(American Samoa (ASA) is a number 6, so they will get the African face, which is clearly wrong).

I'm not a coder at all, put I suspect there is something wrong with the code, which causes some regions to be seen as African or South American, when that is not the correct region.

Personally I've added some more code, to make the number 6 show, and made an Oceanian region.

**Comment by Maradonna90** [comment]
Th is is as intended. The numbers refer to FM ehtnicities, which sometimes can be a bit broad, like Asian or Mediterranean as far as i remember.

And of course we can not divide by every ethnicity. We had to group some smaller ones together as well to make it manageable and be able to generate pictures

**Comment by Freddyzo777** [comment]
Is it also intented that the if "Scandinavian" in [n1_ethnic, n2_ethnic]:
p_ethnic = "South American" is written like that, and not "scandinavian" two times?

At least for my save, if I didn't do anything all my American Samoan players would end up with african faces. (which wasn't ideal in for me) So I made a few changes, and added a new region and added a bit more code to use the number 6. Now it's working for my new region.
