### ISSUE TITLE
[BUG]Genrator not generating after button click

### ISSUE THREAD

**Issue by pino1983** [Maradonna90/NewGAN-Manager#208]
I created a profile, selected the rtf file and the place for the faces, but nothing happens when i click the button
![image](https://github.com/Maradonna90/NewGAN-Manager/assets/148722932/faaf7043-0e79-42b4-a797-20393a07c4ab)

**Comment by JoeTin23** [comment]
having same issue even when running admin

**Comment by coolguyswag69420** [comment]
also having the same issue

**Comment by pino1983** [comment]
Solved it, there was another folder in the faces folder which i had to select

**Comment by PhilC1993** [comment]
Same issue here, no response to the generate button

**Comment by szkatu** [comment]
doesn't work for me either
