### ISSUE TITLE
[BUG] Highlighting RTF file in the windows explorer pop up when selecting RTF causes a Microsoft Word encoding pop up every time

### ISSUE THREAD

**Issue by 034georgie** [Maradonna90/NewGAN-Manager#209]
Not really breaking - but curious to know if anyone has an idea why this is happening? It can be really annoying having to do this every time I have to run NewGan.

![image](https://github.com/Maradonna90/NewGAN-Manager/assets/72174486/d6d4ba31-f9e6-411b-a927-2c697a4dac71)

**Comment by Ayal1** [comment]
Bizarre, though I don't think this is a NewGAN-Manager issue directly. You could try assigning a different default program to open RTF files such as notepad and see if that works.
