### ISSUE TITLE
Faces don't show up in game

### ISSUE THREAD

**Issue by rewasew** [Maradonna90/NewGAN-Manager#210]
The new udpdate doesn't seem to work for me. Have been able to use the program without issues in the past, both on FM24 and previous games. I play on a save that was transferred from FM23 and the faces remained, but when I tried to do it again with the new update it doesn't work. I'm not much of a coder, but I've checked the config-file and it seems as the player ID:s are mapped to faces but they simply don't show up. I have tried restarted the game, clearing cache and reloading the skin. I don't know if it matters, but the save file was corrupted a week ago, and I've been playing on the overwrite backup save ever since. 

I would appreciate any help :)

**Comment by Ayal1** [comment]
Answered in #186 
Quoted here for future use:
> Open the config.xml which is located in (Documents\Sports Interactive\Football Manager 2024\graphics\faces\FMNEWGANv2 + Update 1) with a text editor. (notepad++ in preferred in Windows).
Use "Search and Replace" functionality in text editor.
Search for "graphics/pictures/person/" and replace with "graphics/pictures/person/r-".
Save the file. Reload the skin, it should work.

**Comment by rewasew** [comment]
This didn't work for me, but I actually played around with it and removed the r- from the config file, and then it worked. I had already done this step as I saw an old reddit post about it, and thought it was fixed in the new update, ehich was why I didnät mention it in my post. But it started working for me again when I searched and removed all "r-". I have no idea why this made it work, but maybe it can be of help to you.

**Comment by ricardoalves-dev** [comment]
> This didn't work for me, but I actually played around with it and removed the r- from the config file, and then it worked. I had already done this step as I saw an old reddit post about it, and thought it was fixed in the new update, ehich was why I didnät mention it in my post. But it started working for me again when I searched and removed all "r-". I have no idea why this made it work, but maybe it can be of help to you.

Thank you a lot, man! It worked for me as well at FM23

**Comment by Geo-fury** [comment]
> This didn't work for me, but I actually played around with it and removed the r- from the config file, and then it worked. I had already done this step as I saw an old reddit post about it, and thought it was fixed in the new update, ehich was why I didnät mention it in my post. But it started working for me again when I searched and removed all "r-". I have no idea why this made it work, but maybe it can be of help to you.

This worked for me too on FM23, thanks a bunch
