### ISSUE TITLE
Can't copy to Sports Interactive Folder[BUG]

### ISSUE THREAD

**Issue by ztobes** [Maradonna90/NewGAN-Manager#211]
When I try and copy the unzipped NEWGANv3 folder into the sports interactive graphics folder, I get an error as the files try to copy. "failed to upscale" is what I see as the progress bar for copying stays at 0%. If I try and copy one folder at a time i.e. African, the progress bar estimates about 7 hours and 30 minutes for just the 1GB of data. This slow copying is only occurring for the NEWGAN data. Not sure what may be going on.

**Comment by Ayal1** [comment]
There was an issue with the version that was uploaded. It's now fixed and I've updated the download link now, it's now this link: https://www.mediafire.com/file/r9356ov67s2gz9l/FMNEWGANv3.zip/file

**Comment by ztobes** [comment]
Works great now, thanks!
