### ISSUE TITLE
Not generating faces[BUG]

### ISSUE THREAD

**Issue by XanUtd** [Maradonna90/NewGAN-Manager#216]
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/13889598/newgan.log)
When generating the faces nothing happens. 
I followed all the steps to install. 

It is asking for Player UID.

![Screenshot 2024-01-10 155215](https://github.com/Maradonna90/NewGAN-Manager/assets/156213412/c0eae36e-55fa-4c00-b0f7-874e79490990)

OS: Windows 11

I do not know where to find the newgan.log
RTF-File 
[Regen Faces start.zip](https://github.com/Maradonna90/NewGAN-Manager/files/13889441/Regen.Faces.start.zip)

**Comment by Ayal1** [comment]
You are using the incorrect view when generating the RTF file
