### ISSUE TITLE
[BUG] Config file not populating

### ISSUE THREAD

**Issue by redfox-87** [Maradonna90/NewGAN-Manager#222]
**Describe the bug**
As of yesterday the newgan app is not populating the config file correctly

**To Reproduce**
1. Image directory and RTF pointing towards the correct files and folders
2. New save so using Generate (but tested with an old profile for overwrite) and checking the duplicate box
3. No error message when finished, it is acting as if it is all correct
4. config files looks like the attached

**Expected behavior**
Config file to be populated and new faces to be created when reloading skin in game

**Screenshots**
Attached config file

**Desktop (please complete the following information):**
 - OS: Windows 10

**Attachments**
![Screenshot 2024-01-23 175045](https://github.com/Maradonna90/NewGAN-Manager/assets/157523582/719095f7-c7d0-4117-bc4c-6fd3d59a9ad4)

Add your `newgan.log` and RTF-File

**Comment by redfox-87** [comment]
Resolved issue on own

**Comment by Ayal1** [comment]
Any idea what you did differently?

**Comment by redfox-87** [comment]
Not too sure. I just uninstalled and deleted all associated files, including the config file in the graphic face folder and started again.
