### ISSUE TITLE
NewGAN not writing to Config file[BUG]

### ISSUE THREAD

**Issue by oabbott** [Maradonna90/NewGAN-Manager#229]
I'm having an issue with NewGAN all of a sudden. Was working fine on several different save files until today. The program opens, allows me to create a profile, and goes through the process of mapping with a 'finished :)'  message to confirm, but nothing is ever written to the config file so when reloading my game there are no faces.

I have tried starting as admin, restarting my computer, using different save files, and have uninstalled and reinstalled NewGAN entirely, but I still have this issue. 

Are there any known fixes for this?

Thanks!

**Comment by n3-rd** [comment]
How were you finally able to fix this?
