### ISSUE TITLE
Error Open the App

### ISSUE THREAD

**Issue by Wayne190477** [Maradonna90/NewGAN-Manager#237]
![fdbfgbfgbfgb](https://github.com/Maradonna90/NewGAN-Manager/assets/167476387/be1434a2-f305-4b72-b8c9-22e789ceeed8)
**Describe the bug**
when i open the app appears that error , already reinstalled and still the same ..

**Comment by n3-rd** [comment]
Right click and open as administrator

**Comment by Wayne190477** [comment]
> Right click and open as administrator

already did , still the same error.

**Comment by kcioantunes** [comment]
I'm also having the same problem. I've already reinstalled it and run it as administrator and it doesn't work. What else can be done?

**Comment by kcioantunes** [comment]
I reinstalled it, choosing to install it on all machines and then ran it as administrator on my main user and it started working again.

**Comment by Ayal1** [comment]
> I reinstalled it, choosing to install it on all machines and then ran it as administrator on my main user and it started working again.

this is the current solution, if it's still happening after trying it then I'm afraid there's no known solution as things stand
