### ISSUE TITLE
[BUG] wrong player ID format in config.xml

### ISSUE THREAD

**Issue by Kambo2137** [Maradonna90/NewGAN-Manager#240]
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/15279868/newgan.log)
[regeninfo.zip](https://github.com/Maradonna90/NewGAN-Manager/files/15279886/regeninfo.zip)

The process runs fine, the only issue preventing me from saying it's fine was that the entries format was incorrect so I had to remove all "r-" from each line, like for example:

> record from="Central European/Central European9121" to="graphics/pictures/person/r-1915562036/portrait"
> record from="SAMed/SAMed1066" to="graphics/pictures/person/r-1915506563/portrait"

I used to run previous versions and I didn't encounter this kind of issue. Could I fix something with my setup so that I won't have to change this data manually as above while updating newgens pictures?

**Comment by Ayal1** [comment]
Use the previous version of the program, 1.3.1, for Football Manager 2023 and earlier. Version 1.4.0 should only be used for Football Manager 2024 (and onward assuming they keep the same formatting in future editions).
