### ISSUE TITLE
[BUG?] "Ethnicity has no faces left for mapping"

### ISSUE THREAD

**Issue by jonapoul** [Maradonna90/NewGAN-Manager#42]
**Describe the bug**
When I run every regen in my game through version 1.1 of the program, my log file is filled to the brim with the line:

```
Ethnicity SpanMed has no faces left for mapping. Skipping player XXXXXXXXXX
```

As a result, some of the Spanish regens in my game aren't getting faces assigned to them.

**To Reproduce**
Run the supplied regen_search RTF file through the app and check the log.

**Expected behavior**
Ideally I'd like to see faces get re-used if they run out of unique values, maybe by a configuration setting or something.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 10 64-bit

**Attachments**
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/5685431/newgan.log)
[regen_search.txt](https://github.com/Maradonna90/NewGAN-Manager/files/5685432/regen_search.txt)
I renamed the RTF to .txt because GitHub doesn't accept .rtf extensions.

**Comment by jonapoul** [comment]
By the way, I very much appreciate this project! It really does help with immersion in the game and I love it so much ❤️

**Comment by Maradonna90** [comment]
This should be covered with #33 and is planned for v1.2.0 release.
