### ISSUE TITLE
Invaldi RTF file should throw an error window

### ISSUE THREAD

**Issue by Maradonna90** [Maradonna90/NewGAN-Manager#51]
if a rtf file with the wrong view was exported it should abort the generation process and throw an error window

**Comment by chifte1976** [comment]
Where can I find .rtf file?

**Comment by Maradonna90** [comment]
what do you mean?

**Comment by chifte1976** [comment]
I've installed the program, unzipped pictures files in graphics folder, run the program and nothing happened (parsing rtf message). Should I by myself create Regen info.rtf file or? I'm sending you some printscreens. Happy holidays!

Адвокат Оливер ИлиевскиБулевар 1-ви Мај бр. 148/27000 Битола, Република Северна Македонија+38975449198
Mr. Oliver Ilievski, Attorney at Law
Bulevar 1-vi Maj br. 148/2
7000 Bitola, Republic of North Macedonia+38975449198


Напомена: Информациите содржани во оваа електронска порака можат да бидат ДОВЕРЛИВИ и ПРИВИЛЕГИРАНИ и тие се наменети за користење само од страна на примателот (-ите) наведени погоре. Доколку читателот на оваа порака не е лицето на кое таа му е наменета, Ве информираме дека какво било ширење, дистрибуирање или умножување на оваа комуникација, или кој било дел од нејзината содржина, е строго забрането. Доколку сте ја примиле оваа порака по грешка, Ве молиме да ја препратите до испраќачот и да ја избришете оригиналната порака и сите нејзини копии од Вашиот компјутерски систем.

 
Disclaimer: The information contained in this e-mail may be CONFIDENTIAL and PRIVILEGED and is intended only for the use of the recipient(s) named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication, or any of its contents, is strictly prohibited. If you have received this message by error, please re-send it to the sender and delete the original message and any copy of it from your computer system. 

    On Sunday, January 3, 2021, 4:51:56 PM GMT+1, Marco <notifications@github.com> wrote:  
 
 


what do you mean?

**Comment by Maradonna90** [comment]
this is not a support forum. Check the installation guide from Ayal.

https://www.youtube.com/watch?v=iJqZNp0nomM
