### ISSUE TITLE
Something is wrong with #76 and/or Solomon Islands [BUG]

### ISSUE THREAD

**Issue by grafnase** [Maradonna90/NewGAN-Manager#64]
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/6071945/newgan.log)
**Describe the bug**
When I try to generate faces in any matter in my current save, it simply does not work. I think I have successfully isolated where the problem lies. From the newgan.log file, I can see where the mapping stops. It is always a player from the Solomon Islands (not always the same one, but one from the Solomon Islands) and there is a number (I do not know what it stands for) 76 in the log file. It always stops at the first player containing that number. In NEWGAN itself, I see the "map to player" message, but nothing happens. I can click stuff and close the program, but it won't do anything. As you say in the FAQs, opening the log file repeatedly while the process is running shows that the mapping stops at that particular kind of player. Very frustrating!
Note: I had previously replaced faces in this save file, including several players from the Solomon Islands, and the bug did not happen. So maybe this is due to the latest FM update??

**To Reproduce**
Well, see my log file, you apparently can only reproduce this by having a player with the mystical number 76 from the Solomon Islands in your RTF file.

**Expected behavior**
I expected my faces to be replaced.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Attachments**
Have attached my newgan.log File

**Comment by Maradonna90** [comment]
Can you show me your RTF file?

**Comment by grafnase** [comment]
[RTFs.zip](https://github.com/Maradonna90/NewGAN-Manager/files/6075104/RTFs.zip)
Here you go! :)

**Comment by Maradonna90** [comment]
Thanks. Can you show me e.g David Leon in Player Search with the SCRIPT FACES view? The view might be broken after the current patch :(

**Comment by grafnase** [comment]
![leon david script faces view](https://user-images.githubusercontent.com/79943263/109790727-ff08ff00-7c11-11eb-9885-edb46f104aa6.jpg)

**Comment by Maradonna90** [comment]
Looks like the view is broken in some instances. FML

**Comment by grafnase** [comment]
Damn you, Sports Interactive! :(
Can you say if a change to the view can fix it or do you need to address the issue in 1.3.0?

**Comment by Maradonna90** [comment]
I would need to address it in a quickfix.
