### ISSUE TITLE
Players not assigned/Incorrectly assigned in 1.2.1

### ISSUE THREAD

**Issue by KYIdols** [Maradonna90/NewGAN-Manager#71]
**Describe the bug**
Ethnicitys 11,12,15 and 16 bring up errors. Many Ethinicticitys are incorrecly assigned (10 For example is issued mainly to Caucasen players (ie scottish) within the game but Asian faces in Newgan Manager)

**To Reproduce**
NewGan Manager 1.2.1, Latest Football Manager Patch

**Expected behavior**
All players, regardless of Ethnicity to be correct mapped

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Attachments**
Add your `newgan.log` and RTF-File

[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/6410065/newgan.log)

**Comment by Maradonna90** [comment]
ehtnicities 11, 12, 15 dont exists. Its a bug in the view.

Ethnicity 10 should be Asian. It is nearly the only value for Chinese, Korean, Japanese (etc) players. So either its a bug in the view as well, or the players actually have asian ethnicity (check the 3D face, it should tell)

Before the patch the were some Asian ethnic players in Brazil for example. Maybe you can provide a screenshot for one of those Scottish newgens with ethnicity 10?

**Comment by KYIdols** [comment]
Hey. Please see below. I have a batch of players with no noticable ties to an Asian Country with an Asian FaceGen. Obvously as 11, 12, 15 and 15 do not exist, I have many thousands of players with no face at all

![20210501213221_1](https://user-images.githubusercontent.com/83512572/116794473-1571f080-aac5-11eb-8894-d07e6b9344d9.jpg)
![20210501213229_1](https://user-images.githubusercontent.com/83512572/116794474-16a31d80-aac5-11eb-832b-c2bee42e3f3b.jpg)
![20210501213241_1](https://user-images.githubusercontent.com/83512572/116794476-17d44a80-aac5-11eb-88fd-af4122323fe6.jpg)

**Comment by Maradonna90** [comment]
I mean what are their 3D generated faces? You can see then if they are actual from asian ethnicity or not.

**Comment by Maradonna90** [comment]
ah, there is no dated view. The view was the same all the time.

**Comment by KYIdols** [comment]
I didn't change anything, view or otherwise unless I'm mistaking what you are saying

**Comment by Maradonna90** [comment]
The view in the background of your screenshot is not the original view. The age column doesn't exist there. Check the RTF file how the data looks.
