### ISSUE TITLE
[BUG]RTF invalid when first row has empty 2nd NAT

### ISSUE THREAD

**Issue by vincewu51** [Maradonna90/NewGAN-Manager#76]
**Describe the bug**
When the player in the first row of the RTF has no 2nd NAT, replace faces gives an 'invalid RTF' error. If 2nd NAT is added, the error gives away. 

**To Reproduce**
Use any RTF without 2nd NAT in the first row and click 'replace faces'. 

**Expected behavior**
Finished

**Screenshots**
![image](https://user-images.githubusercontent.com/24503553/122659511-be37e600-d12d-11eb-9cf8-1cc4826c8417.png)

**Desktop (please complete the following information):**
windows

**Attachments**
Add your `newgan.log` and RTF-File

**Comment by Maradonna90** [comment]
can you provide the RTF-file?

**Comment by xaser-one** [comment]
Hey, just to add a little more info on this:
The regex in the is_rtf_valid function seems to be too restrictive - it only matches lines with 2 nationalities, meaning if every player in the file only has 1 nationality, the validation fails. Also player names with special chars (dot, dash, apostrophe) never match.

Example on [pythex.org](https://pythex.org/?regex=(%5C%7C%5Cs*%5B0-9%5D%7B8%2C%7D%5Cs*)(%5C%7C%5Cs*%5BA-Z%5D%7B3%7D%5Cs*)%7B2%7D(%5C%7C%5B%5Cs*%5Cw*%5D%2B)(%5C%7C%5B%5Cs*%5Cd%2B%5D%2B)%7B3%7D%5C%7C&test_string=%7C%202000115129%7C%20BRA%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%7C%20Paulo%20Alexandre%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%201%20%20%20%20%20%20%20%20%20%7C%205%20%20%20%20%20%20%20%20%20%7C%209%20%20%20%20%20%20%20%20%20%7C%20%0A%7C%20-------------------------------------------------------------------------------------------------------------------%7C%20%0A%7C%202000115130%7C%20BRA%20%20%20%20%20%20%20%7C%20POR%20%20%20%20%20%20%20%7C%20Jordan%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%201%20%20%20%20%20%20%20%20%20%7C%2015%20%20%20%20%20%20%20%20%7C%203%20%20%20%20%20%20%20%20%20%7C%20%0A%7C%20-------------------------------------------------------------------------------------------------------------------%7C%20%0A%7C%202000418249%7C%20SRI%20%20%20%20%20%20%20%7C%20AUS%20%20%20%20%20%20%20%7C%20Mohamed%20M.%20Mendis%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%201%20%20%20%20%20%20%20%20%20%7C%2015%20%20%20%20%20%20%20%20%7C%204%20%20%20%20%20%20%20%20%20%7C%20&ignorecase=0&multiline=0&dotall=0&verbose=0)

**Comment by Maradonna90** [comment]
@xaser-one good point. Thats should probably solve the problem.
