### ISSUE TITLE
[ISSUE] It has worked, but only for every player outside my own club?

### ISSUE THREAD

**Issue by gleenyguy** [Maradonna90/NewGAN-Manager#77]
This is not a bug, I just think I have done something wrong. I am in the year 2032 with my save and most of my team are regens, and so I was hoping this would give them a real personality to those animated faces. However I have just finished with everything, and the only faces which have been generated with the facepack are all except my own players who still have their boring default faces. 

Any help would be much appreciated. Also apologies if I've posted this in the wrong place, I am new to github.

Thanks.

**Comment by Ayal1** [comment]
I'm guessing you found out you excluded your own players from the search. It's a common thing to forget.
