### ISSUE TITLE
Some faces refuse to show on MacOS

### ISSUE THREAD

**Issue by bennytee1980** [Maradonna90/NewGAN-Manager#78]
**Describe the bug**
Not Displaying correctly on MacOS
Config creates correctly and works fine when tried on a Windows PC but some faces randomly do not appear on Mac
Not even sure if its anything you can fix but i'm new to Mac so maybe you know something I don't

**Desktop (please complete the following information):**
 - OS: Mac OS, Bug Sur, M1 Chip

**Comment by Maradonna90** [comment]
Not really, if its in the config.xml and the facepack is in the right directory. The only thing you could try is clear cache and reload the skin.

Closing
