### ISSUE TITLE
[BUG] App crashes and not opening

### ISSUE THREAD

**Issue by QooKoo** [Maradonna90/NewGAN-Manager#79]
Hi, I would like to say thank you for your innovative program that makes me more satisfied playing FM.

However, from last week the program didn't launch and I can't figure it out why it crashes.

I succeed to open and use it very well often but now it doesn't.

I saw readme you said "If the app crashes for some reason open an issue and please provide the newgan.log file. It helps to figure where exactly the app crashed combined with your description.", so I upload newgan.log file here.

Thanks again for your program and I hope we find some way to make program open again :)

[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/6847183/newgan.log)

**Comment by Maradonna90** [comment]
Yeah i really dont understand how the app gets into that state.

Only solution right now is to delete the folder `%localappdata%\Programs\NewGAN-Manager\` and re-install.

**Comment by QooKoo** [comment]
Oh it worked! 

Thanks for your help and with your innovative program too
