### ISSUE TITLE
NewGAN Manager Application won't launch [BUG]

### ISSUE THREAD

**Issue by wildman171** [Maradonna90/NewGAN-Manager#80]
The NewGAN Manager application won't launch on Windows 10. I click on it and the little loading circle pops up next to the mouse, but nothing happens. I'm pretty sure the log even shows it as attempting to launch too. It did launch (v.1.2.0) earlier and I had actually used sort of used it. I realized I messed up and had linked the wrong folder for the "Select image directory." I had only selected up to the "face" folder and not the actual "FMNEWGANv2" folder. Before I realized that, I had tried a bunch of times to generate faces, but obviously it didn't work. When I realized that, I deleted the other profiles I made and tried to relaunch the application, but it wouldn't work. I tried uninstalling and reinstalling it a bunch of times but to no avail. I later realized that there was a newer version, v.1.2.1 and I tried using that and it didn't launch either.

I know that the original video Zealand posted about this has a solution for this in the description: 
In %localappdata%\Programs\NewGAN Manager open the "app" folder and copy the .config folder.
Then got back to the NewGAN Manager folder and paste the .config folder and overwrite.

I tried this is and I couldn't get it to work. I am not really sure what it meant though, and maybe I did something wrong. The .config folder is in the %localappdata%\Programs\NewGAN Manager\app\newganmanager folder so I am not sure what pasting the .config folder in the NewGAN Manager folder would actually. Regardless, I did that and it still didn't launch.

Here is the log.
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/6897496/newgan.log)

**Comment by Ayal1** [comment]
Fully uninstall NewGAN-Manager through "Add or Remove Programs" in the windows start menu.
Then go to %localappdata%\Programs\ and delete any folders that have "NewGAN" in the name. Afterward, reinstall with the latest installer.

**Comment by wildman171** [comment]
Thank you, that solved the problem!
