### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by savegobbos** [Maradonna90/NewGAN-Manager#82]
It was working at first, but after a few days the program wont open

[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/7025873/newgan.log)

I have uninstalled/reinstalled.    I have attempted zealands .config solution but I might be doing it incorrectly.

**Comment by nxmkhoa** [comment]
you could fix that by going in to C:\Users\yourdevicename\AppData\Local\Programs and delete the NewGAN-manager folder then going into control panel to uninstall the NewGAN-manager app and then reinstall it, it will work now. 

My guess on why this is happening is that the profile created is conflicting with the default (no profile) so the app crashed and cannot load into the UI.

**Comment by Maradonna90** [comment]
hard to tell what the issue is. In doubt save your profile data and reinstall fresh.
