### ISSUE TITLE
Many South American Players mapping as African

### ISSUE THREAD

**Issue by Joseamm23** [Maradonna90/NewGAN-Manager#85]
I applied the faces to my save and when I saw it in detail, most of the players in Peru, Colombia, Bolivia, Argentina, and the other south american countries looked African instead of South American. I checked the config xml and indeed its generating the faces from Africa. How can I solve this?

**Comment by Joseamm23** [comment]
![3d faces](https://user-images.githubusercontent.com/89942208/131743549-a65e1de1-5569-48f3-9728-f074399fe207.PNG)
![wrong images](https://user-images.githubusercontent.com/89942208/131743566-3959aa91-2f6f-4088-8296-679e2d52b74e.PNG)

As you can see in the images, the 3d faces references other skin colours too. The problem is not only the skin colour, but the region the app is taking the images from.

**Comment by Maradonna90** [comment]
should be fixed with #83
