### ISSUE TITLE
[BUG] bug on map player to

### ISSUE THREAD

**Issue by duongtran26** [Maradonna90/NewGAN-Manager#86]
I have the same bug . I tried to uninstall many times, install to the latest version, but it still crashes, the black bar only works 1\4 to stand. do you have any way to fix it?
![242365603_10208572165618212_2460048313679930513_n](https://user-images.githubusercontent.com/91175828/134300504-6dcbd0a4-0c47-4fea-8963-dc4d70175a04.jpg)

**Comment by Ayal1** [comment]
sounds like #62 and you're just not directing the program to the correct folder
