### ISSUE TITLE
[BUG] Image generation maxes out at 21550

### ISSUE THREAD

**Issue by richy279** [Maradonna90/NewGAN-Manager#87]
Kind of piggybacking off of a previous bug regarding the progress bar reaching around 20%. I have the facepack installed and linked to the correct folder, as well as the .rtf file linked up. Now albeit this is a fairly large database with 135,834 regens currently in the database (year 2031) however it seems that, according to the log file, generation appears to reach 21550/135834 before stopping. Is this an upper limit? I do have Allow Duplicates checked.

**Screenshots**
![image](https://user-images.githubusercontent.com/92750505/137783132-d7723544-db68-4b9e-b6ec-8f5e23ea3c8a.png)

OS: Windows 10

Log file attached
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/7367611/newgan.log)

**Comment by Maradonna90** [comment]
if you still have your rtf file that would be great.

**Comment by Maradonna90** [comment]
Closed for lack of information. Feel free to reopen with the rtf file.
