### ISSUE TITLE
Fix Layout being cut off

### ISSUE THREAD

**Issue by Maradonna90** [Maradonna90/NewGAN-Manager#9]
https://files.gitter.im/577a08ccc2f0db084a214c33/zK6s/grafik.png

**Comment by lukeejay** [comment]
![updatedGui](https://user-images.githubusercontent.com/9654390/100483982-8d8d5200-30f2-11eb-981b-d3b85ae5b1c4.jpg)

If you want some help I can make a pull request?

**Comment by Maradonna90** [comment]
Sure go ahead. Look splendid!
