### ISSUE TITLE
Updated Linux Build

### ISSUE THREAD

**Issue by FunWithUrban** [Maradonna90/NewGAN-Manager#90]
Any chance for an updated Linux build? I saw that you supported it in the read me but was upset to see a bug stopped support in version v1.0.1. 

If not what issues will I run into using the old version and two is there any way to use the current version with wine?

**Comment by Maradonna90** [comment]
I haven't looked into it yet. The beeware framework fails building under Ubuntu 14. You can basically clone this repo, create a python venv, install the requirements and use `beeware dev`to run it.

**Comment by FunWithUrban** [comment]
Im not a very advanced user but I can try following some tutorials to get it working for myself. I would love if Linux got some love in the next update though!

**Comment by linusnorton** [comment]
Thanks @Maradonna90

**Comment by linusnorton** [comment]
Any chance of a new release?

**Comment by linusnorton** [comment]
Ah no worries, found it: https://github.com/Maradonna90/NewGAN-Manager/suites/4618869684/artifacts/124942024

**Comment by linusnorton** [comment]
Hmm no AppImage file in there

**Comment by FunWithUrban** [comment]
Incredibly thankful that you are working on this @Maradonna90. Is there any way to download this now or do we have to wait for a new release?

**Comment by Maradonna90** [comment]
if you want an AppImage you have to wait for the next release. Which probably will be a quickfix for the OSX issue.
