### ISSUE TITLE
[BUG] - Not opening on M1 Mac

### ISSUE THREAD

**Issue by mauricioblum** [Maradonna90/NewGAN-Manager#91]
**Describe the bug**
I'm trying to open the 1.3.0 version on a M1 Mac without success.
The app only displays an error message saying it can't be opened.
I already tried opening with Rosetta (x86 compatibilty layer). 
When I do this I get a different message saying the app crashed, with the following Traceback:

````
Traceback (most recent call last):
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/__main__.py", line 4, in <module>
    main().main_loop()
  File "NewGAN-Manager.app/Contents/Resources/app/newganmanager/app.py", line 430, in main
    fh = logging.FileHandler('newgan.log')
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "NewGAN-Manager.app/Contents/Resources/Support/Python/Resources/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/newgan.log'
````
 

**To Reproduce**
1. Install the app dragging it to the Applications folder
2. Click on the app
3. See error message
4. Close the app, right-click on it and then in the 'Get Info' option.
5. Check 'Open with Rosetta'.
6. Close it and try to open again.
7. See error with traceback.

**Expected behavior**
Application should start.

**Screenshots**
I've recorded a video since I think it's more clear. Watch [here](https://streamable.com/q3ynfb)

**Desktop (please complete the following information):**
 - OS: macOS Monterrey 12.0.1 - Macbook Air M1 2020

**Attachments**
Don't have it since I don't get to that point.

If you need any more information just let me know!

**Comment by Maradonna90** [comment]
Several people are having the same issue on MAC. This will be top priority

**Comment by mauricioblum** [comment]
I was able to run the app by cloning the repo, installing deps and running with `briefcase dev`. 
I'm not a Python developer so I really did not know much of what I was doing, but it worked. I'm available if you need any help getting this to work for everyone.

**Comment by jhalt13** [comment]
Hello, I have a 2017 Macbook Air with Mac OS High Sierra Version 10.13.6. I am having this same issue, however I do not think my computer has Rosetta capability. Any help would be great.

**Comment by ehalen** [comment]
Hi, has there been any update on this issue? I've been having the same problem

**Comment by ishqhakhidzr** [comment]
Having the same issue here with intel macbook pro 2020 with Catalina 10.15.7. Any updates? Thanks

**Comment by BillyJudd** [comment]
Having the same problem on MacBook Pro 2019.

**Comment by tjegbejimba** [comment]
If anyone needs a temp fix this person's instructions worked for me on my 2020 intel MacBook air with Monterrey.
https://fm-base.co.uk/threads/newgan-facepack.164663/page-39#post-2552722

**Comment by kierdoyle** [comment]
The temp fix is either no longer working or doesn't work on M1/M1Pro's on Monterey

**Comment by ghdevin** [comment]
Any updates on this bug? Having the same issue and the temporary fix/workarounds do not work.

**Comment by rickvanoverbeek** [comment]
Doesn't work for me. Hopefully this will get fixed soon.

**Comment by nosovae-dev** [comment]
quick workaround: 
1) open Application folder
2) open context menu for NewGAN-Manager -> Show Package Contents
3) open /Applications/NewGAN-Manager.app/Contents/Resources/app/newganmanager/app.py in text editor
4) change line 430     fh = logging.FileHandler('newgan.log')  ->  fh = logging.FileHandler('/tmp/newgan.log')
5) save the file and re-open application

also I did the same for /Applications/NewGAN-Manager.app/Contents/Resources/app/mapper.py line 18

Enjoy!


P.S. after that application log files will be place in /tmp folder

**Comment by rickvanoverbeek** [comment]
> quick workaround:
> 
> 1. open Application folder
> 2. open context menu for NewGAN-Manager -> Show Package Contents
> 3. open /Applications/NewGAN-Manager.app/Contents/Resources/app/newganmanager/app.py in text editor
> 4. change line 430     fh = logging.FileHandler('newgan.log')  ->  fh = logging.FileHandler('/tmp/newgan.log')
> 5. save the file and re-open application
> 
> also I did the same for /Applications/NewGAN-Manager.app/Contents/Resources/app/mapper.py line 18
> 
> Enjoy!
> 
> P.S. after that application log files will be place in /tmp folder

This worked! Thanks!!

**Comment by shlatt99** [comment]
> quick workaround:
> 
> 1. open Application folder
> 2. open context menu for NewGAN-Manager -> Show Package Contents
> 3. open /Applications/NewGAN-Manager.app/Contents/Resources/app/newganmanager/app.py in text editor
> 4. change line 430     fh = logging.FileHandler('newgan.log')  ->  fh = logging.FileHandler('/tmp/newgan.log')
> 5. save the file and re-open application
> 
> also I did the same for /Applications/NewGAN-Manager.app/Contents/Resources/app/mapper.py line 18
> 
> Enjoy!
> 
> P.S. after that application log files will be place in /tmp folder

Thanks, this worked. If anyone else is having this problem, note that the numbered steps will ensure you can open the app, but you do also need to edit line 18 in mapper.py before the faces will update.

**Comment by ak1234-stack** [comment]
This still doesn’t work for me! Any other ideas?

**Comment by nosovae-dev** [comment]
> This still doesn’t work for me! Any other ideas?

Do you have the same text of the issue? Could you paste the text error here, please

**Comment by kierdoyle** [comment]
Doesn't work for me either, but I'm not running in Rosetta (just opening package contents and through the terminal). 

Here's my error message:

/Applications/NewGAN-Manager.app/Contents/MacOS/NewGAN-Manager ; exit;          
kierdoyle@Kierans-MacBook-Pro-2 ~ % /Applications/NewGAN-Manager.app/Contents/MacOS/NewGAN-Manager ; exit;
zsh: killed     /Applications/NewGAN-Manager.app/Contents/MacOS/NewGAN-Manager

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

**Comment by keikeikk12** [comment]
Thank you!
The program worked this way.

But when it shows finish, the face is still there😭

**Comment by Maradonna90** [comment]
[NewGAN-Manager-Installer-Mac-v1.3.1.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7918378/NewGAN-Manager-Installer-Mac-v1.3.1.zip)
can someone test this version?

**Comment by ak1234-stack** [comment]
> [NewGAN-Manager-Installer-Mac-v1.3.1.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7918378/NewGAN-Manager-Installer-Mac-v1.3.1.zip)
> can someone test this version?

This one works! 💪🏽

**Comment by keikeikk12** [comment]
> [NewGAN-Manager-Installer-Mac-v1.3.1.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7918378/NewGAN-Manager-Installer-Mac-v1.3.1.zip) can someone test this version?

It started up without any problems and the program is running.
It could be another problem, but it doesn't change my face😭

**Comment by alexanderroland** [comment]
> [NewGAN-Manager-Installer-Mac-v1.3.1.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7918378/NewGAN-Manager-Installer-Mac-v1.3.1.zip)
> can someone test this version?

This one also doesn't work for me. Here is the error I received from Terminal:

`The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000039c7b70 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}`

**Comment by alexanderroland** [comment]
> 

I just used `codesign --force --deep --sign` on the application and now it opened!

**Comment by Maradonna90** [comment]
@alexanderroland I don't really understand whats happening there tbh. Open a new issue for it

@nosovae-dev @mauricioblum @pelmered @jhalt13 @BillyJudd @ehalen @ysmf @tjegbejimba @kierdoyle @ghdevin @rickvanoverbeek can some of you test the pre-release version: https://github.com/Maradonna90/NewGAN-Manager/files/7918378/NewGAN-Manager-Installer-Mac-v1.3.1.zip ?

**Comment by mauricioblum** [comment]
> @alexanderroland I don't really understand whats happening there tbh. Open a new issue for it
> 
> @nosovae-dev @mauricioblum @pelmered @jhalt13 @BillyJudd @ehalen @ysmf @tjegbejimba @kierdoyle @ghdevin @rickvanoverbeek can some of you test the pre-release version: https://github.com/Maradonna90/NewGAN-Manager/files/7918378/NewGAN-Manager-Installer-Mac-v1.3.1.zip ?

For me, on Rosetta, it opens and runs without any crashes!
Generate, preserve and overwrite all working normally. 
Without Rosetta only shows the error "Application cant be opened.

**Comment by alexanderroland** [comment]
> For me, on Rosetta, it opens and runs without any crashes!

Thanks, I just checked is using Rosetta for the first time and the bug I reported in the other thread didn't occur. (Users need to manually activate Rosetta by right-clicking the app > Information > mark checkbox 'Open with Rosetta.)

I'll check the functionality soon.

**Comment by athanasiosMitrentsis** [comment]
> Without Rosetta only shows the error "Application cant be opened.

I can confirm that the application is opening without any issues with rosetta activated :)
I get an error though when trying to generate images ('The RTF file is invalid'). But I doubt that it is related to this version ;) Thx a lot

**Comment by ghdevin** [comment]
> [NewGAN-Manager-Installer-Mac-v1.3.1.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7918378/NewGAN-Manager-Installer-Mac-v1.3.1.zip)
> can someone test this version?

Able to open and run using Rosetta, but 'Preserve' function does not work. Is true for all Mac users? 

On my next season, followed the same instructions and updated the RTF file, but it is not updating faces with the face pack.

**Comment by itsmetambui** [comment]
> > [NewGAN-Manager-Installer-Mac-v1.3.1.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7918378/NewGAN-Manager-Installer-Mac-v1.3.1.zip)
> > can someone test this version?
> 
> Able to open and run using Rosetta, but 'Preserve' function does not work. Is true for all Mac users?
> 
> On my next season, followed the same instructions and updated the RTF file, but it is not updating faces with the face pack.

I'm on a Mac Pro M1max with Monterey, and I'm able to run the app without Rosetta and Preserve also worked for me.

**Comment by Arkylis** [comment]
> [NewGAN-Manager-Installer-Mac-v1.3.1.zip](https://github.com/Maradonna90/NewGAN-Manager/files/7918378/NewGAN-Manager-Installer-Mac-v1.3.1.zip) can someone test this version?

This version worked on my MBP without any issues.

**Comment by antmad99** [comment]
I have problems when creating the profile t
<img width="1007" alt="Captura de pantalla 2022-02-02 a las 17 19 41" src="https://user-images.githubusercontent.com/98842452/152193709-d6808f1f-795e-4eb3-bfa2-3b00d10ff644.png">
he following message appears

**Comment by itsmetambui** [comment]
> I have problems when creating the profile t <img alt="Captura de pantalla 2022-02-02 a las 17 19 41" width="1007" src="https://user-images.githubusercontent.com/98842452/152193709-d6808f1f-795e-4eb3-bfa2-3b00d10ff644.png"> he following message appears

You'll need to import and use the View provided. https://youtu.be/pmdIkhfmY6w?t=682

**Comment by ysmf** [comment]
> Having the same issue here with intel macbook pro 2020 with Catalina 10.15.7. Any updates? Thanks

Trying it again on another mac, imac late 2012, same error message i guess (screenshot). I've tried the 1.3.1.zip in the thread here and that does not open at all, had to force quit. Still doesn't open on Catalina 10.15.7 for both macbook and imac. Thanks
![Screenshot 2022-02-02 at 7 27 22 PM](https://user-images.githubusercontent.com/59951030/152227375-c77e0f60-5a13-4f4c-8c9c-b39c5da5c6eb.png)
.

**Comment by Maradonna90** [comment]
@ysmf looks like you haven't updatet it properly. The code referenced is old.

**Comment by Maradonna90** [comment]
My conclusion so far. Use Rosetta if available, otherwise it should open. Any objections?

**Comment by keikeikk12** [comment]
Is there a way to deal with the problem of the face not changing?

**Comment by ysmf** [comment]
> @ysmf looks like you haven't updatet it properly. The code referenced is old.

Sorry, but how do I get it updated? Is it the same download link? Thanks

**Comment by SirJohnA** [comment]
Same problem here. Tried to edit the py files and it didn't work. The provided download link to version 1.3.1 points to 1.3.0.
I am on a M1 MacBook Pro with Monterrey 12.3.1

**Comment by APPetrovic** [comment]
Hi all!
I have the same problem with version 1.3.1. 
Just a message “can’t open” when try to launch without Rosetta. Or “Application has crashed” and much code if Rosetta is used.
And I can’t edit py files - no permission. 
Nothing helps.
When trying to launch older versions, app just stops without any messages. 
Have any ideas?
Mac M1 2021, Monterey 12.5.1.
