### ISSUE TITLE
Fake Player support

### ISSUE THREAD

**Issue by Subtleslight** [Maradonna90/NewGAN-Manager#99]
The facepack does not appear to work for saves with Fake players and staff turned on. The original FM generated faces take precedence over pictures, and turning them off just gives silhouettes. Given that there aren't many players using this option, this is probably a low priority enhancement. But I feel it should be noted as a known "issue".

**Comment by Ayal1** [comment]
They're not newgens, they are literally regens as in they are the players in the game's database just regenerated to have a different name. This is why even with this setting ticked, PSG will always have Brazillian and Argentinian wingers (Neymar and Messi).

**Comment by Subtleslight** [comment]
I am well aware that they are not newgens. I even say it in the title. I know it's just fake names. That doesn't not change the fact that I would like to be able to use this facepack to replace all of the generated ones. I'm not saying this is a bug at all. Just potentially a low priority enhancement for the future.

**Comment by Maradonna90** [comment]
highly questionable if we will ever support it, but I leave it open for now.

**Comment by Maradonna90** [comment]
I close the issue. If we reconsider this feature I will reopen it again.
